### ISSUE TITLE
Status stays after leaving VSC

### ISSUE THREAD

**Issue by m4xc4v413r4** [iCrawl/discord-vscode#10]
After closing VSC the status disappears and all the info this extension gives disappears, which is obviously as designed, but then the status "playing: visual studio code" comes back.

So, i'm standing here with VSC closed and it still says i'm using it.

**Comment by KingDGrizzle** [comment]
Huh. Was unable to reproduce. What version of VSCode / Windows / Discord do you have?

For VSCode, `Help -> About`, for Discord: `Stable / PTB / Canary`, and for Windows.. Well. Its Windows

**Comment by iCrawl** [comment]
Aside from that, there is nothing I can do. The only thing you can do to potentially prevent this is add the program as a game on Discord.
If that still doesn't do the trick, we are out of options here. It's not the fault from the extension and rather a problem with the RPC client/Discord itself.

**Comment by m4xc4v413r4** [comment]
@KingDGrizzle I'm on the latest Stable of both (1.18.1 64 bit for VSC, not sure the version on Discord), Windows 10.

@iCrawl Well, I can't say for sure it's caused by the extension and not Discord it self but it is connected to this new info system because I always had VSC added as a game and it showed that it was being used (as it is normal for anything added to the list), and now it has this strange bug.

I'll leave a video showing what happens so it is clearer.
If it is fixable or not that's another thing, but at least this will exist here for future reference.

Video explanation: VSC is added to games list, open and close VSC with extension disabled to show it appears and disapears as intended from the status and game list, do the same thing with extension enabled, it shows the new more detailed status as intended, but when VSC is closed the status changes to the simple old one even though there is no VSC open and it doesn't even show on the game list.

[Video here](https://streamable.com/fbav2)
