### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by Hitoshi1337** [iCrawl/discord-vscode#100]
My vscode is not updating when im restarting vscode it always shows only first file i started editing and then nothing is updating only editing time

**Comment by iCrawl** [comment]
This might be a regression I introduced in https://github.com/iCrawl/discord-vscode/commit/aa9fcf94ded6b0081a655967c57807a72d765eb4

I will have a look.

**Comment by iCrawl** [comment]
Published a fix in `2.12.1`, should be out soon.
