### ISSUE TITLE
View Repository button (Discord Status) is not working

### ISSUE THREAD

**Issue by Banik1103** [iCrawl/discord-vscode#1006]
![image](https://user-images.githubusercontent.com/62890322/114869563-6ca27080-9df7-11eb-893d-b5ce8d75762f.png)

This button is not working when clicked. If I recall correctly, it was added recently.

**Comment by jacany** [comment]
Discord RPC buttons don't actually do anything if it's your status that the buttons are on, the buttons do work for other people though.

**Comment by Banik1103** [comment]
Oh, didn't know that, thank you!

**Comment by alexcaussades** [comment]
thanks for the information
