### ISSUE TITLE
"View Repository" leaks HTTP auth if specified in the repository remote URL

### ISSUE THREAD

**Issue by Cynosphere** [iCrawl/discord-vscode#1008]

**Comment by iCrawl** [comment]
Yeah, for now there is not much to be done here. Clone via SSH or continue to clone via HTTPS but not with the access token and instead let yourself be prompted for a username and password where the password is the token.

**Comment by Cynosphere** [comment]
The project uses isomorphic-git, so neither of these are a solution, other than just hiding "View Repository" entirely.

**Comment by iCrawl** [comment]
Since you gave no further information on if you are using gitlab, github, gogs, gitea or bitbucket, I will assume whatever this implementation is uses a `https://username:password@example.com/someOrg/someRepo.git` or `https://personalaccesstoken@example.com/someOrg/someRepo.git`, correct?

**Comment by Cynosphere** [comment]
GitLab. First scheme.

**Comment by iCrawl** [comment]
Should be fixed in v5.6.3
