### ISSUE TITLE
Bug: Presence doesn't update when editing unpublished repository

### ISSUE THREAD

**Issue by Purpzie** [iCrawl/discord-vscode#1009]
The presence refuses to update at all (for example when switching between files) if you're editing a repository that hasn't been published yet. This probably has to do with the "view repository" button, since setting `discord.removeRemoteRepository` to `true` makes the presence work again.

**Comment by jacany** [comment]
What do you mean exactly by unpublished? Like no remote URL or?

**Comment by jacany** [comment]
Fixed in #1010
