### ISSUE TITLE
Cant Connect

### ISSUE THREAD

**Issue by x7b4** [iCrawl/discord-vscode#1011]
![image](https://user-images.githubusercontent.com/81993995/115543014-95b87a80-a2a9-11eb-8803-35b4d2d95ea2.png)
![lol](https://user-images.githubusercontent.com/81993995/115543059-a49f2d00-a2a9-11eb-8ad8-4b32783007db.jpg)

**Comment by x7b4** [comment]
can anyone help me fix this

**Comment by provinceinnovation** [comment]
Duplicate of #85
