### ISSUE TITLE
{Lang} doesn't seem to work with discord.LargeImage

### ISSUE THREAD

**Issue by integralfx** [iCrawl/discord-vscode#103]
![image](https://user-images.githubusercontent.com/16512539/48178907-595e6180-e370-11e8-83ed-565d029b32c9.png)

Settings:
```
    "discord.detailsDebugging": "Fixing one bug and adding two more",
    "discord.detailsEditing": "Adding bugs to fix later",
    "discord.lowerDetailsDebugging": "{null}",
    "discord.lowerDetailsEditing": "{null}",
    "discord.lowerDetailsNotFound": "",
    "discord.largeImageIdle": "",
    "discord.lowerDetailsIdle": "{null}",
    "discord.workspaceElapsedTime": true,
    "discord.largeImage": "Editing a {Lang} file",
```

![image](https://user-images.githubusercontent.com/16512539/48178937-86ab0f80-e370-11e8-98b8-238a095ccadf.png)

As shown above, {Lang} is shown rather than Java.

**Comment by iCrawl** [comment]
`3.0.2` should show up after the Microsoft approval step 👍
