### ISSUE TITLE
The View Repository button doesn't work

### ISSUE THREAD

**Issue by hql1991** [iCrawl/discord-vscode#1038]
System: Windows 10 64-bit
VS Code: v1.56.0
Discord: Stable 84265 (acb9d12)

Issue:
Use VS Code to open a git repo, and then I'm able to see the status updated to discord, with a View Repository button at the bottom. However, if I click on it nothing happens.
![image](https://user-images.githubusercontent.com/10230464/117500790-f4c8f100-af31-11eb-99ff-14c7c6812a55.png)

Checking the Discord Presense output console it shows that the URL has been sent successfully.
![image](https://user-images.githubusercontent.com/10230464/117500853-13c78300-af32-11eb-9509-3f7113b01037.png)

**Comment by hql1991** [comment]
Please let me know if you need more info such as logs, etc. However I think if you have a windows machine this issue should be easily reproduced.

**Comment by iCrawl** [comment]
https://github.com/iCrawl/discord-vscode/issues/1006

**Comment by hql1991** [comment]
Thanks for the quick reply!

**Comment by decov** [comment]
how did you get access to that discord presence output?
