### ISSUE TITLE
When you are in the voice channel, you can see an empty corner of the icon.

### ISSUE THREAD

**Issue by Zamur650** [iCrawl/discord-vscode#1060]
Here are screenshots.
![image](https://user-images.githubusercontent.com/57483029/119220414-ae1fed00-bb14-11eb-90f3-3c1be4373928.png)
![image](https://user-images.githubusercontent.com/57483029/119220453-dc053180-bb14-11eb-86ab-44031707f85b.png)

**Comment by iCrawl** [comment]
None of the icons have empty corners. That is a Discord issue.
