### ISSUE TITLE
discord-rpc getting spammed

### ISSUE THREAD

**Issue by Ascor8522** [iCrawl/discord-vscode#1074]
From what I read, the status should only be updated
* every 5 sconds https://github.com/iCrawl/discord-vscode/blob/82b9d24844cec795784d339e616727ad01f594ab/src/extension.ts#L35
* when the extension is started https://github.com/iCrawl/discord-vscode/blob/82b9d24844cec795784d339e616727ad01f594ab/src/extension.ts#L52
* when the active editor is changed https://github.com/iCrawl/discord-vscode/blob/82b9d24844cec795784d339e616727ad01f594ab/src/extension.ts#L53
* when the content of a document changes or the document is saved https://github.com/iCrawl/discord-vscode/blob/82b9d24844cec795784d339e616727ad01f594ab/src/extension.ts#L54
* when starting a debug session https://github.com/iCrawl/discord-vscode/blob/82b9d24844cec795784d339e616727ad01f594ab/src/extension.ts#L55
* when exiting a debug session https://github.com/iCrawl/discord-vscode/blob/82b9d24844cec795784d339e616727ad01f594ab/src/extension.ts#L56

but somehow, when idling in VSCode, whithout any tab open not doing anything, the presence is updated every second (sometimes multiple times).

![image](https://user-images.githubusercontent.com/17651422/120013876-9dbeb500-bfe1-11eb-9c18-3fba8d7f1afd.png)

**Comment by iCrawl** [comment]
Yes, it doesn't really matter. Your client is limiting it properly.

**Comment by Ascor8522** [comment]
Still, its impact is limited but it's still a problem and it is spamming the VSCode output tab...
