### ISSUE TITLE
Presence not working on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by WickedWizard3588** [iCrawl/discord-vscode#1086]
Hey,

I switched to Ubuntu 20.04 LTS recently, and when I installed VSCode, Discord, I noticed the Rich Presence wasn't working. I had installed Discord from https://discord.com/ and not using `flatpak` or `snap`. I followed the instructions on issue https://github.com/iCrawl/discord-vscode/issues/77#issuecomment-435622205.

I've already reinstalled thrice, but still of no avail.

**Comment by diskxo** [comment]
I have the same problem, someone can help us? Thanks

**Comment by WickedWizard3588** [comment]
This is not a perfect solution, but what I did was,
I uninstalled both VSCode and Discord
Then reinstall Discord using the .deb and VSCode using snap

This fixed it for me
