### ISSUE TITLE
Please remove annoying popup when everything is fine.

### ISSUE THREAD

**Issue by ALIENQuake** [iCrawl/discord-vscode#109]
Hi
Please remove annoying popup when everything is fine. It's annoying and unnecessary. If something works, you won't need to yet another popup 'It works!'.

**Comment by iCrawl** [comment]
Please read through the available options before opening an issue:

https://github.com/iCrawl/discord-vscode/blob/master/package.json#L107-L111

**Comment by ALIENQuake** [comment]
@iCrawl This option is a workaround, my feedback was about user experience design but anyway thanks.

**Comment by iCrawl** [comment]
I don't see how this is a workaround. It clearly is a bad idea to remove pop ups over all.

**Comment by ALIENQuake** [comment]
@iCrawl Of course it would be a bad idea to remove ALL popups for ALL cases. That's why I only requested removal of the `Successfully connected to Discord RPC` popup because when everything is fine, there is no need for the popup.

**Comment by KingDGrizzle** [comment]
@ALIENQuake @iCrawl what if, instead, we change the connecting icon in the status bar to say connected, wait 5 seconds, then hide it? (I am aware this is a closed issue, but my thoughts still apply)

**Comment by ALIENQuake** [comment]
@KingDGrizzle Yep, it's still better than popups which steal you attention. Popups should be used only for problems, not for saying "Everything is OK and we really, REALLY need to tell you that. Now close popup!"
