### ISSUE TITLE
Linux: RPC not triggering

### ISSUE THREAD

**Issue by l-zeuch** [iCrawl/discord-vscode#1117]
Hello there!

I am running under Debian 10 (Buster) and use the PTB Discord client branch. Here's the information about my VSCode:
```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 4.19.0-17-amd64
```

I tried the following:
- Disabling, then re-enabling the extension
- Reinstalling the extension
- Reloading VSCode several times
- Reloading the Discord Client
- Quitting Discord + VSCode, then starting Discord first, after that VSCode
- Restarting my PC

All of which to no avail. 

Strangely enough, the extension over at https://github.com/LeonardSSH/vscord works just fine. Right after installing Leonard's extension, the RPC triggers and shows that I am playing VSCode, however I would prefer your extension, as it integrates with Git and the like, which I almost exclusively use on my code projects.

If you need additional information, please do not hesitate to ask away!

Thanks in advance!

**Comment by iCrawl** [comment]
No idea where I would even start debugging.

The repository you linked (and others) uses the same library to connect to discord.

**Comment by l-zeuch** [comment]
Update: Strangely enough reinstalling everything fixed it...
I'm as baffled as you - as you said, the other extension uses the same library, so there's that.
I'll close this issue now, as the error does not seem to be on your end, rather it was on mine.

So yeah, for anyone running Debian: 
Try reinstalling VSCode, that fixed it for me.

Cheers though!
