### ISSUE TITLE
Stuck on "Connecting to Discord..."

### ISSUE THREAD

**Issue by BeetMacol** [iCrawl/discord-vscode#1119]
After I installed it for the first time it worked, but for some reason it stopped working after a restart and I can't do anything to make it work again. Tried reinstalling the extension, running discord before vscode and the other way, restarting the connection. Nothing worked. I'm on Arch Linux, running [Discord Canary from AUR](https://aur.archlinux.org/packages/discord-canary/), vscode is Code - OSS version 1.56.2.

Edit: I just managed to get it working once again. I disabled the extension, restarted my machine, started discord and then started vscode and re-enable the extension.  
Problems with the connection is a huge issue on Linux and it should not be that hard to just use the extension. I know there are a few similar issues on this repository, but what I am experiencing is not exactly the same and workaround is different, so I will leave the issue open. In #1117 the author states it works with the [vscord](https://github.com/LeonardSSH/vscord) extension, but for me it's not the case.

**Comment by iCrawl** [comment]
Theres nothing this extension can do to alleviate the problems you mention.
