### ISSUE TITLE
Hide Rich Presence After Inactivity

### ISSUE THREAD

**Issue by larsenv** [iCrawl/discord-vscode#114]
I would like a feature where if the RPC detects I haven't been actively using Visual Studio Code in a set amount of minutes, the rich presence will hide. This way, if I'm AFK, using other apps or I forget that it's open, then it won't show up until I am using it again.

I was using this plugin until I realized the fact I couldn't get it to hide after inactivity was annoying. People even asked me if I was OK because I'd leave the program on overnight and it showed I was using Visual Studio Code for many hours.

**Comment by iCrawl** [comment]
Thought about this a lot already, decided against it. Simply not worth it. Just turn off your PC or close VSCode. There is absolutely no reason to keep it running.

**Comment by larsenv** [comment]
Yeah but I have a bad habit of leaving apps open, tabs in Google Chrome, code editors, etc. while they eat up RAM. The JetBrains and Atom RPC both have the feature, and I quit using Atom and I'm not sure how to fix my habit.

**Comment by l0c4lh057** [comment]
I'd also like to have this feature. I keep my stuff running all the time to access it as fast as possible and to not wait a minute before I can start doing something. VSC starts up pretty fast, but other IDEs I use take very long and I just never close IDEs because of them, even VSC stays open just because the other IDEs formed a habit to never close something.

**Comment by iCrawl** [comment]
That's all nice and dandy, but I have no idea how you want me to reliably detect "inactivity".
Don't forget that I have just a few APIs to work with inside of VSC. Additionally, again, I don't see why I should support bad habits.
No other `game` that uses RPC has this, if you leave open your games that use RPC they also don't just disappear after some time.

**Comment by l0c4lh057** [comment]
Maybe I will take a look into this, even though I never worked with VSC extensions. Just in case I manage to do this, would you accept the feature if I did a pr?
