### ISSUE TITLE
Never connects

### ISSUE THREAD

**Issue by Milo123459** [iCrawl/discord-vscode#1143]
The presence just seems to never connect.
```
[08/07/2021 18:32:27 - ERROR] Encountered following error while trying to login:
Error: connection closed
```
Not sure what is causing that, I'm not closing discord.

Sometimes it says
```
[08/07/2021 18:33:47 - INFO] Creating discord-rpc client
[08/07/2021 18:33:47 - INFO] Successfully connected to Discord
```

but still doesn't display anything.

**Comment by Matix-Media** [comment]
Have you tried to manually connect it after VS Code started using the command palette? When I start up VS Code, it yells at me to that it can't connect. But if I do it via the command palette, it works.

**Comment by Milo123459** [comment]
Yes I have tried and it did not work

**Comment by Matix-Media** [comment]
Hm. Guess I'll open a ticket with my problem then.

**Comment by sotre-develoepr** [comment]
mine says it's connected but it's spewing out
`[22/07/2021 19:08:19 - DEBUG] Loading git extension
[22/07/2021 19:08:19 - TRACE] Git extension not activated, activating...`
repeatedly. the presence also doesn't show up on discord

**Comment by iCrawl** [comment]
If the FAQ in the readme doesn't solve your problem, there's nothing you or I can do from what I know.
