### ISSUE TITLE
Repository button not working

### ISSUE THREAD

**Issue by Matix-Media** [iCrawl/discord-vscode#1148]
When I open a project in VS Code, and I connect VS Code with discord, then it shows a open repository button. Which is pretty cool. The problem is, that nothing happens when I click on that button.

**Comment by TymanWasTaken** [comment]
For some reason in discord you can't click buttons on your own status, they should work for other people

**Comment by validity-check** [comment]
This is to do with Discord's API, not related to this repo. If you go through closed issues, many people have already said this.

**Comment by Matix-Media** [comment]
Ok 👍
