### ISSUE TITLE
Linux - Isn't connecting to Discord

### ISSUE THREAD

**Issue by kanetjuh** [iCrawl/discord-vscode#1154]
![image](https://user-images.githubusercontent.com/50002439/125524591-6109a5a2-0df4-4fe5-9143-85ae27db3230.png)

My VS-Code won't connect to Discord (I installed Discord on the program 'Ubuntu Software' itself), i did this also for Visual Studio Code.

**OS Information:**
- Ubuntu 20.04

**Comment by monotiller** [comment]
Hi, sorry if I'm answering on someone else's behalf, however, from the [FAQ](https://marketplace.visualstudio.com/items?itemName=icrawl.discord-vscode#troubleshooting):

> Linux: Discord versions installed using `flatpak` or `snap` need modifications in order to support IPC. In order to avoid this (and as Discord itself suggests) you should download it from discord.com
> 
> References:
> https://github.com/flathub/com.discordapp.Discord/issues/29
> https://github.com/iCrawl/discord-vscode/issues/77#issuecomment-435622205
> https://github.com/iCrawl/discord-vscode/issues/85#issuecomment-417895483

Just a coincidence that I've just read the above and seen this issue within the span of a few seconds. Hope this helps.

**Comment by iCrawl** [comment]
If none of the above works, there's nothing you or I can do.

**Comment by bschaatsbergen** [comment]
Interesting way to close a ticket, it's definitly still not solved. 

![image](https://user-images.githubusercontent.com/58337159/165259076-46518acc-8dbf-4796-b3da-801fd4d5012e.png)
