### ISSUE TITLE
Disable if Discord is not running

### ISSUE THREAD

**Issue by vekat** [iCrawl/discord-vscode#117]
Hello. I like this extension and right now it does its job.

However, I am one of the people that do not have Discord as a startup application on my system, and every time I open VSCode without having Discord running, I get the error popup telling me that discord-vscode was not able to connect to Discord's RPC. This quickly became annoying.

Would it be possible to only show this error if Discord is in fact running? Perhaps there's a difference between the error you get when the RPC is not up, and the error you get when a connection problem happens?

Additionally, it would be helpful if the `manual reconnect` shortcut was also a visible command within the `(Ctrl | Cmd) + Shift + P` menu.

**Comment by iCrawl** [comment]
There is not really a way to detect if the user has discord running or not and suppressing a "specific" error message just for that purpose is quite bad because of false positives.

The other thing can be done though.

**Comment by vekat** [comment]
Are you using `discord.js`'s RPC module?

**Comment by iCrawl** [comment]
That's right.

**Comment by iCrawl** [comment]
Since this is released now and the former one can't really be done, I'll close this.
If theres a way in the future to do this, it should be opened as a new issue.
