### ISSUE TITLE
Windows - Error when connecting to Discord Canary

### ISSUE THREAD

**Issue by sanikdah** [iCrawl/discord-vscode#1179]
Hi, I'm using Discord Canary, and recently this extensions just gives an error if I try to connect to Discord RPC.  The error is attached, please help!
![image](https://user-images.githubusercontent.com/72118300/127714158-8c3313c2-70aa-4430-a483-fd5b68042c47.png)

**Comment by iCrawl** [comment]
If the FAQ in the readme doesn't solve your problem, there's nothing you or I can do from what I know.

**Comment by RH203** [comment]
I have same problem with u, but that error message only pops up when I don't open Discord at all, it usually happens when I just turned on my PC. The only way to solve this is to open your discord, after that `CTRL+SHIFT+P` and reload your Visual Studio Code. I hope this resolves your problem. Xd
