### ISSUE TITLE
Update Objective-C icon

### ISSUE THREAD

**Issue by SNDST00M** [iCrawl/discord-vscode#1181]
Maybe the Apple icon would be better. It's used in https://github.com/topics/objective-c

![808841241142755358](https://user-images.githubusercontent.com/82655227/127773002-84e014f4-a4da-4433-93ac-6e06396289c8.png)

**Comment by iCrawl** [comment]
No, I don't think so.

**Comment by SNDST00M** [comment]
Alright though I don't like the color or design of the current one. Cann't find another replacement :/
