### ISSUE TITLE
changing image support

### ISSUE THREAD

**Issue by elementISH** [iCrawl/discord-vscode#1197]
add an option where you can change the image of a language you want lets say i want to change the image of the TXT file extension so i drop a link for it and its changed, or if this feature is already there please tell me how to do it 😅

**Comment by iCrawl** [comment]
Discord doesn't allow dynamically changing images.

**Comment by Bejasc** [comment]
@iCrawl does this mean it is not possible to provide a URL to an image, to be used as the big image? 
It would be great to use a project logo here.
