### ISSUE TITLE
[Request] Preference to display overall time rather than per-file

### ISSUE THREAD

**Issue by EthanC** [iCrawl/discord-vscode#12]
Love the Extension! Hoping for a preference to allow for the entire time elapsed that you've been working on a project for that session to be displayed in Discord rather than the time you've been working on a specific file. 

Thanks

**Comment by iCrawl** [comment]
Good suggestion!

**Comment by Netox005** [comment]
How about making this a triple setting? Let `discord.elapsedTime` be 'all', 'file' or 'disabled'/'off'
