### ISSUE TITLE
View Repository Button shown for private repos

### ISSUE THREAD

**Issue by Destaq** [iCrawl/discord-vscode#1209]
I am working on a project linked to a private GitHub repository. However the _View Repository_ button is still present on my Discord profile - even though the repository isn't viewable by the public.

![image](https://user-images.githubusercontent.com/61620873/129959131-1224d93f-a2ef-4ff1-9c7f-dd4621fdb9c8.png)

Equally, I've encountered this before on other people's profiles - a button which is present, but does nothing when clicked, which leads to believe that this is also due to the private repository bug.

Platform: macOS Big Sur
Discord version info: Stable 94010 (5b2a0b4) Host 0.0.263 OS X 11.0.0 (20.5.0)
VS Code version: 1.59.0

**Comment by iCrawl** [comment]
There is no way to detect whether a repo is private or not simply from git itself.
