### ISSUE TITLE
"View Repository" not working in Discord Desktop version

### ISSUE THREAD

**Issue by subhendudash02** [iCrawl/discord-vscode#1319]
The button "View Repository" is not working in Discord Desktop but working on mobile.
OS : Windows 10 Single Language (Version 10.0.19042.1288) and Ubuntu Focal Fossa (Version 20.04.3 LTS)
Discord version: 1.0.9002

**Comment by iCrawl** [comment]
https://github.com/iCrawl/discord-vscode/issues/1006#issuecomment-820789203

**Comment by subhendudash02** [comment]
Oh, got it. Thank you!
