### ISSUE TITLE
Error Notification

### ISSUE THREAD

**Issue by Modelmat** [iCrawl/discord-vscode#14]
Can we have it so that when "Discord" is not open, or I do not have internet, that it does not show this error message? I find it to be really annoying (the RPC cannnot connect). If it is better, aside from where it is detected to be open and you hvave internet, then the error message can be shown. Otherwise, maybe a log message in the little bar at the botom.

**Comment by KingDGrizzle** [comment]
In fact, I think the latest update did just that (if Crawl released it).

Check if you have an F1 - Discord Disable command of sorts. That should do what you want.

**Comment by Modelmat** [comment]
Is the latest version 1.30? And yes, there is a disable, but it only annoys me on startup.

**Comment by iCrawl** [comment]
There is no reliable way to detect whether you have an active internet connection or the discord process is running.
If you put `discord.silence: true` in your global `settings.json` it will silence those errors.
