### ISSUE TITLE
[Feature Request] Ability to change file icons for different languages

### ISSUE THREAD

**Issue by Proxxaaa** [iCrawl/discord-vscode#149]
It would be amazing to be able to customise what icons we use for our large display icons. Currently, the icon for JSON files seems a bit ugly, but it would be AMAZING if I could change it to the icon from my file icon theme:
![json](https://user-images.githubusercontent.com/40413110/50730727-eaa84500-1121-11e9-96d9-38173918fb45.png)
OR change the icons to their respective icons from the icon theme automatically!

**Comment by Proxxaaa** [comment]
I've gone file-digging and found that there aren't even any files in the extension folder itself.

**Comment by Proxxaaa** [comment]
Aaagh, I probably should've known, but I've never actually looked at the whole RPC thing in [the dev area](discordapp.com/develepors) very well.

**Comment by Proxxaaa** [comment]
Thanks anyway, sad that discord doesn't support it like that. If there's some way to automatically make the client and everything, it'd probably take a crapload of code, mostly dedicated to HTTP.

**Comment by Techman** [comment]
@vladfrangu Do you know how to set this up in the Discord API panel? I am wanting to change the icons to the ones featured in [file-icons](https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons) like [atom-discord](https://atom.io/packages/atom-discord) uses.

**Comment by itsmeboy0** [comment]
> If you want to change the large or small images, you'll need to provide your own custom client ID in the settings for this extension.

@vladfrangu  Discord has silently added the ability to use an image link for the large image key ([Source](https://twitter.com/realBas950/status/1474072825103331330), large image key only but that's something).
