### ISSUE TITLE
Extension disfunctionning with C files

### ISSUE THREAD

**Issue by Zyrophr** [iCrawl/discord-vscode#15]
Hey there !
I've got a lil' problem to make this extension working with the C language on VSCode.
I'm on discord Canary & Fedora 26.

All of my .c projects are showing as "Idling" for Discord.
Works really good with every other language I tried 👍 

Also, when switching to a working file (like settings.json) , when I go back to my C project it shows that I'm always editing my settings !

![2017-12-09-150226_1920x1080_scrot](https://user-images.githubusercontent.com/31597162/33796316-1e5f416a-dcf2-11e7-8850-f24c22621425.png)

**Comment by iCrawl** [comment]
Thanks for the bug report!
