### ISSUE TITLE
Can't connect to discord

### ISSUE THREAD

**Issue by Davoleo** [iCrawl/discord-vscode#150]
Gif of the error
![crjxhnfdgc](https://user-images.githubusercontent.com/24458276/50922934-f5c5e280-144b-11e9-9549-4da01c120a7a.gif)

Extension Version: 3.2.1

VS-Code version:
![image](https://user-images.githubusercontent.com/24458276/50922762-8ea82e00-144b-11e9-8674-6de728d38341.png)

Couldn't find any other log about it also on discord
If you need more info just tell me

**Comment by iCrawl** [comment]
If its not:
https://github.com/iCrawl/discord-vscode/issues/77#issuecomment-443592725
or
https://github.com/iCrawl/discord-vscode/issues/85#issuecomment-417895483

Theres nothing I can do.
