### ISSUE TITLE
write EPIPE error

### ISSUE THREAD

**Issue by CloroxBleach6** [iCrawl/discord-vscode#155]
this has been working fine until now, whenever I try to connect it give me a write epipe error

![image](https://user-images.githubusercontent.com/39915632/51360366-516e1c80-1a99-11e9-90ec-40c0e93d2c7d.png)

also, I'm using visual studio insiders edition

**Comment by iCrawl** [comment]
Nothing I can do against that, its discord-rpc which this extension relies on.
