### ISSUE TITLE
Using Remote - SSH extension will expose your SSH IP

### ISSUE THREAD

**Issue by phamleduy04** [iCrawl/discord-vscode#1617]
![image](https://user-images.githubusercontent.com/32657584/177026054-cb2c22aa-8206-40a9-bb0c-c9f50b0e4a87.png)

**Comment by CookieGMVN** [comment]
![image](https://user-images.githubusercontent.com/73780382/177031929-a65420e2-4999-4cb1-8c86-1da640dfb610.png)
Just open your SSH config file, find your SSH config and change the host's name in Host field.
