### ISSUE TITLE
 After 24 hours time restarts

### ISSUE THREAD

**Issue by PedroLuisBrilhadori** [iCrawl/discord-vscode#1639]
I didn't restart either discord or vscode. After 24 hours the counter goes back to 0

before 24h:
![image](https://user-images.githubusercontent.com/74775672/180045862-99cc4a2a-3a6a-424b-b786-456a8caada3f.png)

after:
![image](https://user-images.githubusercontent.com/74775672/180045889-c5d6b859-2a26-4d05-a759-067c7cd562e0.png)

**Comment by loidnoir** [comment]
because discord cant show more than 24 hours
