### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by willster277** [iCrawl/discord-vscode#1656]
There are 33 open issues from this year, most of which have no response, *none* of which have labels.

There are 12 open PRs from this year (excluding the many dependabot PRs), *none* have a response from the author, *none* have labels.

@iCrawl is this project abandoned? Several of these issues and PRs seem fairly important, but have been ignored for months.

**Comment by iCrawl** [comment]
The project is working as intended and does not need any changes. The PRs are feature requests where most don't conform the standard.

The "issues" are none. Repository button not working? Explained bunch of times, doesn't work if you click on it. It's a discord thing not this extension.
Not working? Certain OS are not supported by discords protocol.
Running in a sandbox? Snap? Flatpack? Yup, neither supported by discord.

There have been no real code changes for almost 2 years and it's been running fine for 99% of the user base.

**Comment by sageyx2002** [comment]
> Troubleshooting
Windows: Do not run your VSCode or Discord as admin, there is no reason to [...]

![image](https://github.com/iCrawl/discord-vscode/assets/104058571/629020f8-3254-4c88-b089-72dc72a129af)

*as long as you don't get an 'Access denied.' in terminal*

> [...] and it just further complicates everything down the line.

A user may stream a game using Anti-Cheat software to their friends and forget to relaunch Discord without administrative permission. If it complicates things, that's on you, not the user. Other extensions too struggle with admin permissions, but at least do not leave uncaught errors if that is the case

![image](https://github.com/iCrawl/discord-vscode/assets/104058571/3e1bfb5e-b40f-4537-97c8-0a5ffafc82e5)

---

> The "issues" are none.

![image](https://github.com/iCrawl/discord-vscode/assets/104058571/30c30f48-aab7-41f9-94d4-7eda51f2e868)

((other (more customizable, not intermittently at best working) extensions, locally hosted RPC clients, game activity, etc. work fine, another issue is listed for you right above))

---

There are issues, they are presented to you in this repository over and over, the most that happens - as pointed out before by OP - is that issues are occasionally closed, or even less often receive a delusional answer about how there would not be an issue at all.
