### ISSUE TITLE
Request to use workspace project icon for largeImageKey

### ISSUE THREAD

**Issue by Alcha** [iCrawl/discord-vscode#17]
For example, when working on my personal bot, I have an `icon.png` file that's the default icon for the project, when editing that workspace, I'd love to have that icon be displayed as the largeImageKey. Another example would be when I forked the discord-vscode repo, there was an Icon.png that would've looked great as the largeImageKey.

I tried adding something myself but I'm not too familiar with TypeScript yet so I know I butchered the specifics. I looked into the setActivity() function and tried to tinker with some stuff on my own fork that ended up looking something like [this gist](https://gist.github.com/Alcha/76865d22ede3364e327cf03bbc1eaedb). 

I know there's gotta be a better way to do it but I just stumbled upon this project and love what it can do so it'll take me some time to get acquainted with TypeScript so I can be more useful.

**Comment by iCrawl** [comment]
This wouldn't be possible with the current way Discord does Rich Presence. You would have to maintain your own fork and build your own .vsix(I think its called that way) and install it every time locally after you keep the fork up2date.

**Comment by Alcha** [comment]
Is the `.vsix` (or w/e it is) the built version of the VSCode extension?

Meaning, I'd have to fork this repo, set it up to use the icon, build/install it locally, and keep it up-to-date?

Am I understanding correctly?

**Comment by iCrawl** [comment]
Yes it is.

And yes you'd have to keep the fork up2date to not miss out on updates, but make the changes you want and manually build your .vsix file and install that in VSCode.

**Comment by Alcha** [comment]
Thanks for the help!
