### ISSUE TITLE
Couldn't connect to Discord via RPC: Error

### ISSUE THREAD

**Issue by LordJudge** [iCrawl/discord-vscode#1704]
Just started getting this error after updating discord on windows and cant find any fixes.

**Comment by XdGoldenTigerOfficial** [comment]
Getting the same error. Even if I try to retry connecting over and over again.
Thank god it isnt just me...

**Comment by m2en** [comment]
I'm experrrincing the same problem
In my environment, timeout error occurs

**vscode version**: 1.71.2 ( git hash: `74b1f979648cc44d385a2286793c226e611f59e7` )
**discord version**: Stable 149549 (1e1ae6d) - Windows 11

I think it's a bug on the Discord API side. (This is just speculation.)

![image](https://user-images.githubusercontent.com/82575685/193053209-a621efa2-022b-4b80-8cc1-b1cff163254a.png)

**Comment by Iqrar99** [comment]
Happened to me as well, but it happened after I accidentally ran my discord as an administrator on windows.

**Comment by m2en** [comment]
Just recently I no longer have the problem in my environment. Unlike the above comment, the cause is unknown. .......

![image](https://user-images.githubusercontent.com/82575685/194246183-44fbd487-25c2-4fa1-a06e-f132a39a42b3.png)

**Comment by lazuee** [comment]
I got the same error above when After installing Discord,.
Just re-open Discord after installing, because it runs with admin perm.

Don't run Discord as admin.

**Comment by Inui-senpai** [comment]
I tried everything I can (re-run Discord PTB and making sure it doesn't run with admin perms _(drag'n'drop not works in progs launched as admin)_, install Discord Stable, etc.), but still get this error. I'm more than sure the problem isn't on my side, it's just that Discord's staff broke something again in one of their updates.
