### ISSUE TITLE
Couldn't connect to Discord via RPC: Error: Could not connect

### ISSUE THREAD

**Issue by pandasoli** [iCrawl/discord-vscode#1728]
I'm getting this error.

I'm using Linux (Ubuntu 22.04.1 LTS (Jammy Jellyfish)).

**Comment by elsamuel27** [comment]
Make sure that both Discord and VSCode are installed by deb packs

**Comment by pandasoli** [comment]
Thx. It is working now. I was using the Discord as a browser application
