### ISSUE TITLE
Doesn't react nicely when discord is shut down

### ISSUE THREAD

**Issue by itslukej** [iCrawl/discord-vscode#18]
![image](https://user-images.githubusercontent.com/8759737/34071702-1b871b4a-e272-11e7-8757-4a7a8db5c995.png)

**Comment by iCrawl** [comment]
This is definitely too little information.

**Comment by pyrox18** [comment]
I'm also having similar issues when Discord isn't running. The extension seems to constantly keep my CPU at ~100% usage and use more RAM than usual, even after failing to connect.

Streamable for reference: https://streamable.com/nklwf

**Comment by iCrawl** [comment]
Is this happening with the standard amount of reconnect attempts?

**Comment by pyrox18** [comment]
Tried with default, 5, 1 and 0, all with the same results.

**Comment by pyrox18** [comment]
Found the issue, it was an infinite recursion in discord-rpc. The above PR should solve it.

**Comment by iCrawl** [comment]
Thank you very much, you are a godsend 🙇
