### ISSUE TITLE
Says its connected to discord but it doesnt appear

### ISSUE THREAD

**Issue by Caiden-P** [iCrawl/discord-vscode#1887]
As the title says it says its connected but it doesnt show anything it used to work then suddenly stopped literally for no reason i restarted both vs code and discord and my pc still, i uninstalled and reinstalled, still, i am not running anything as run as administrator

**Comment by Caiden-P** [comment]
i am on windows

**Comment by Caiden-P** [comment]
AGAIN this used to work, i didnt get a windows update im on 11 it used to work fine now all of a sudden i notice it just doesnt work says connected to discord but it doesnt show any RPC

**Comment by Caiden-P** [comment]
@iCrawl pls help

**Comment by Caiden-P** [comment]
its working for my friend but not me it was working fine for me then suddently stopped for no reason what so ever

**Comment by Caiden-P** [comment]
Spotify RPC works fine everything works except that it just stopped for no reason i didnt install uninstall update or change anything 1 second it was working the next its saying connected but not showing anything on discord

**Comment by Caiden-P** [comment]
my friend helped me fix it

**Comment by sebdc** [comment]
Hey, I'm currently having the same issue. Would you mind sharing how you fixed it?

**Comment by maks1u** [comment]
> my friend helped me fix it

How did u fix it?

**Comment by GitMrZoink** [comment]
Having the same issue here...
