### ISSUE TITLE
"RPC" to "SDK"

### ISSUE THREAD

**Issue by akirataguchi115** [iCrawl/discord-vscode#1889]
https://discord.com/developers/docs/game-sdk/sdk-starter-guide

We should maybe change the wording to SDK as RPC is deprecated.

**Comment by tipakA** [comment]
[RPC](https://discord.com/developers/docs/topics/rpc) (the way of communication with the discord app) isn't deprecated. [Discord-RPC](https://github.com/discord/discord-rpc) (the standalone C++ SDK to implement RPC) is, as it was merged into the full Game SDK, and continues to be supported there just fine in form of [Activities](https://discord.com/developers/docs/game-sdk/activities) that slightly abstract over raw RPC.

Also fairly sure that this extension (or the [`discord-rpc`](https://www.npmjs.com/package/discord-rpc) JS package used under the hood) don't use any native code to even be able to use the deprecated SDK.

**Comment by akirataguchi115** [comment]
Thanks for correcting me!
