### ISSUE TITLE
Couldn't connect to Discord via RPC: Error: Could not connect

### ISSUE THREAD

**Issue by felipecosta003** [iCrawl/discord-vscode#1909]
It always gives this error. I solve it once, but it always comes back

**Comment by Skyknight47** [comment]
how did you solve it? I'm running into the same issue, and have been for the past few weeks

**Comment by Dilettante258** [comment]
> how did you solve it? I'm running into the same issue, and have been for the past few weeks

Open Discord when you want to sync you status by using the plugin.
