### ISSUE TITLE
discord.workspaceElapsedTime default

### ISSUE THREAD

**Issue by bbukaty** [iCrawl/discord-vscode#197]
I was a bit confused to see that the default for the extension is to show the time elapsed working on a single file as opposed to the workspace. I believe the 'time elapsed in workspace' metric is much more informative and useful to someone looking at your activity in discord, and would personally prefer it to be the default behavior. Is there a reason why it is not?

**Comment by iCrawl** [comment]
Hmmm, yea mainly because I didn't want to make this a breaking change. People were already running modified configurations, so changing the default on this (which many people relied on) could cause quite some confusion again.
I will think about switching it for a future version.
