### ISSUE TITLE
No status seems to be displayed in Discord

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [iCrawl/discord-vscode#203]
I was originally getting the "RPC" error; I cleared that up, and am getting no errors, but my Discord still only shows this:

<img width="703" alt="Discord settings, Game Activity, 'No game detected'" src="https://user-images.githubusercontent.com/200/54383550-4e8a4500-4660-11e9-83d1-22713da16559.png">

Is there documentation on how to *use* this, somewhere? The README could use a little beefing-up! 🤣

**Comment by iCrawl** [comment]
Funny you mention it, but there is actually *nothing* you can do or even have to do.

Discord RPC is scarcely documented, the underlying library that is used to make all the IPC interfacing with discord does already pretty much everything it can do to make this work.

Chances are your discord is installed incorrectly more on this here:
https://github.com/iCrawl/discord-vscode/issues/77#issuecomment-443592725
and here
https://github.com/iCrawl/discord-vscode/issues/85#issuecomment-417895483
(The windows one is actually not really a wrong installation, but simply a windows thing, if you run A as admin, the thing A interfaces with, in this case B, needs to be run as admin too)

Or your RPC server inside of discord just died, had that happen to me with spotify here and there. Restarting both usually fixed it, *sometimes*

**Comment by ELLIOTTCABLE** [comment]
Hmmm. Is there a reproducible, simple test-case I can do to make sure I have this all installed correctly?

(I'm on macOS, for context. Discord 0.0.43, VScode 1.32.2.

**Comment by Funeoz** [comment]
Same happening here on Kubuntu 18.10, VS Code 1.32.3, latest version of Discord (can't determine it but updates are always installed).

**Comment by Funeoz** [comment]
Tried to reinstall Discord. Nothing changed.

**Comment by iCrawl** [comment]
https://github.com/iCrawl/discord-vscode/issues/77#issuecomment-411514866

**Comment by NickKaramoff** [comment]
To @ELLIOTTCABLE and others, who may have this problem: I am on macOS too, and today I discovered that although the settings menu says "No game detected", the game _is_ being detected. Just go to any server you're in and find yourself in the members' list — VS Code will show up.

![Settings menu saying "No game detected"](https://user-images.githubusercontent.com/6566248/85037270-69ae0380-b185-11ea-90f9-00195429d45e.png)
!["Game" being detected fine](https://user-images.githubusercontent.com/6566248/85037591-dcb77a00-b185-11ea-9890-6b3bee837b42.png)

(sorry for screenshots in German)
