### ISSUE TITLE
Could not connect - Ubuntu 18.04.2

### ISSUE THREAD

**Issue by mitch1414** [iCrawl/discord-vscode#206]
Operating System: **Ubuntu 18.04.2**
Discord: **0.0.9**
Visual Studio Code: **1.33.0-insider**

Error: `Could not connect`

Hey, been having issues with this can't figure out how to get it to work. Please help.

**Comment by iCrawl** [comment]
https://github.com/iCrawl/discord-vscode/issues/77#issuecomment-443592725

**Comment by mitch1414** [comment]
Didn't work, that's why I made this.

**Comment by iCrawl** [comment]
If neither work, nothing I can do. Support for macOS and Linux is as shitty as it can be, that goes for the official RPC on discords side too.

**Comment by mitch1414** [comment]
Alright, I fixed it. Sorry.
