### ISSUE TITLE
Can't connect to Discord Canary RPC on Ubuntu 16.10 

### ISSUE THREAD

**Issue by RONTheCookie** [iCrawl/discord-vscode#21]
![image](https://user-images.githubusercontent.com/25263210/34452452-dc1d056a-ed47-11e7-9ff0-6dacf986b8c5.png)
VSC is added as a discord "game", if that helps.

**Comment by iCrawl** [comment]
Most likely an issue with https://github.com/devsnek/discord-rpc and not this extension.

**Comment by RONTheCookie** [comment]
I'll try some other apps that use that to see if that's the issue.
