### ISSUE TITLE
When I save a File EONET Error

### ISSUE THREAD

**Issue by PLASMAchicken** [iCrawl/discord-vscode#214]
When i edit a File and save it I get: 
`Error: ENOENT: no such file or directory, open 'C:\e:\gitworkspace\Project\index.js'`

**Comment by iCrawl** [comment]
I don't see how this is related to this extension.

**Comment by PLASMAchicken** [comment]
It comes up in the extensions log:

![image](https://user-images.githubusercontent.com/16088476/55814150-4a7e0580-5aee-11e9-9099-1209dc91867c.png)
