### ISSUE TITLE
Suggestion on file language detection

### ISSUE THREAD

**Issue by benpigchu** [iCrawl/discord-vscode#22]
Currently this extension detect languages by itself with filename, but simply get it from `window.activeTextEditor.document.languageId` may be better. This also makes it possible to display correct language icon for matlab `.m` file and objective-c `.m` file, if user select correct language for themselves.

Also, there may be sub-type of files besides language, we can detect by the extension itself after get the languageId.

**Comment by DusterTheFirst** [comment]
solved in #23?
