### ISSUE TITLE
Couldn't connect to Discord via RPC: [object Object]

### ISSUE THREAD

**Issue by Kaigo11k** [iCrawl/discord-vscode#239]
Hello, I am having this problem when starting VSC, when I start this appears: http://prntscr.com/nez082, when I try to reconnect, this: http://prntscr.com/nez1k2, I saw other issues alike this, but none helped me.

I tried reinstalling the vsc and extension but it did not work

My windows version: [1803]
![winver](https://user-images.githubusercontent.com/37600692/56474528-7df75300-6451-11e9-84b1-a44f10429df3.png)

My vsc:
![vsc](https://user-images.githubusercontent.com/37600692/56474552-d4fd2800-6451-11e9-8374-ec8dd8907472.png)

**Comment by iCrawl** [comment]
https://github.com/iCrawl/discord-vscode/issues/236#issuecomment-483941161
