### ISSUE TITLE
Discord Presence breaks if Discord is restarted and VSCode restart attempts empty

### ISSUE THREAD

**Issue by KingDGrizzle** [iCrawl/discord-vscode#24]
So, I've noticed this weird bug with Discord Presence. (or discord-rpc, one of the two).

The easiest steps to reproduce this is:

- Launch Discord
- Launch VSCode
- Close Discord
- In VSCode, wait till all the errors from IPC connections end (no more popups saying `cannot connect to IPC`)
- Restart Discord
- Run the Enable Discord Presence Command

## What should happen
Everyone is a good boi and resume the rich presence

## What happens
Someone isn't a good boi and well, breaks.

**Comment by DusterTheFirst** [comment]
check out #28
