### ISSUE TITLE
Command not found 

### ISSUE THREAD

**Issue by lothsun** [iCrawl/discord-vscode#246]
Using 3.5.0 on the latest version of vscode produces a "Command not found" error on macOS. Not sure if anyone else is having this issue or not. VSCode version is 1.24.1
![Screen Shot 2019-04-26 at 6 26 02 PM](https://user-images.githubusercontent.com/4888709/56841085-33127c80-6851-11e9-9b7f-d23809ab389c.png)

**Comment by iCrawl** [comment]
I can't really reproduce on 3.5.0 nor 3.5.1

Maybe you should look into updating your VSCode though, 1.24 is horribly outdated.

**Comment by lothsun** [comment]
That’s odd. I tried using the check for updates before I posted this. Told me there were no updates available. Will do and report back.

**Comment by lothsun** [comment]
It’s working now.
