### ISSUE TITLE
Discord Not Detecting

### ISSUE THREAD

**Issue by animatedstick** [iCrawl/discord-vscode#247]
I Installed Discord Presence Using VS Code Extensions Page But It Doesn't Work at All the Extension Seems Good But Discord is Not Detecting is and Even VS Code Doesn't Show and Error :(
I tired Asking support from the Discord Support Server and they Didn't Respond or Helped me they just ignore others.
By the way i'm using discord.py
Thanks!

**Comment by iCrawl** [comment]
<https://github.com/iCrawl/discord-vscode/issues/236#issuecomment-483941161>
<https://github.com/iCrawl/discord-vscode/issues/77#issuecomment-435622205>
<https://github.com/iCrawl/discord-vscode/issues/77#issuecomment-435622205>

**Comment by adyou2** [comment]
me also installed the Discord Presence , but my work in VS cord is not showing in Discord ! , iam using discord in chrome, is there any problem ?

**Comment by iCrawl** [comment]
Yeah this only works with the Desktop app.

**Comment by AkylKa** [comment]
The problem is also present on linux, but most likely the problem is with the rpc connection, either you need to install the Desktop version, or dig further

**Comment by SanDBoom** [comment]
Go to activity status in ur discord and manually select vs code

**Comment by Itsmemartin** [comment]
My discord is picking up vs code, but just wont show up on my profile saying "playing vs code"

**Comment by Itsmemartin** [comment]
It did work on mine, I had to reconnect ¯\_(ツ)_/¯

**Comment by IIHunkaII** [comment]
For everyone who might encounter this issue again I recommend you to make sure the toggle "Display current activity as a status message." is turned on inside Discord's "Activity Privacy" settings.

**Comment by masoshii** [comment]
> For everyone who might encounter this issue again I recommend you to make sure the toggle "Display current activity as a status message." is turned on inside Discord's "Activity Privacy" settings.

Now I'm feeling dumb lol

**Comment by inamis9** [comment]
For me the problem was that I didn't have the 'Share your detected activities with others' setting enabled under activity settings in the discord desktop app!

**Comment by AhmadNoty** [comment]
> For everyone who might encounter this issue again I recommend you to make sure the toggle "Display current activity as a status message." is turned on inside Discord's "Activity Privacy" settings. 

@zenerra Dude, thank you so much! I actually feel dumb now that I know.

For those who are wondering, just make sure the option "Share your detected activties with others" is enabled, and also the extension itself should be enabled too

![Refrence](https://github.com/user-attachments/assets/4ae72609-aed9-4ca8-93a5-dffcfcea05c9)
