### ISSUE TITLE
It's Lua not LUA

### ISSUE THREAD

**Issue by GlorifiedPig** [iCrawl/discord-vscode#272]
It's Lua and not LUA. Please fix this, it's a very common mistake and bothers me deeply.

**Comment by iCrawl** [comment]
https://github.com/iCrawl/discord-vscode/issues/76#issuecomment-414080119

**Comment by SNDST00M** [comment]
This issue applies to all languages that have lowercase characters.
It's the extension that's somehow capitalising all language names.
