### ISSUE TITLE
[Request] Optionally censoring activity

### ISSUE THREAD

**Issue by Mazuh** [iCrawl/discord-vscode#273]
As a developer, I not always want people seeing which file I'm editing. That could be changed on VS Code settings (and keeping today's current behavior as default).

(It's a feature request but I'd like to implement it myself if someones agrees with this "product decision".)

**Comment by kyranet** [comment]
Isn't the property configuration `discord.detailsEditing` not enough? You can change it in your VSCode workspace/global settings without polluting the project's `.vscode/settings.json`.

The default is set here:

https://github.com/iCrawl/discord-vscode/blob/de6c420825225beca8982b995288be2f00ff80e5/package.json#L85

**Comment by Mazuh** [comment]
aw, I didn't knew about this... :thinking: nevermind, then. I'll close this.
