### ISSUE TITLE
[Request] Don't display connection error if Discord is closed

### ISSUE THREAD

**Issue by briman0094** [iCrawl/discord-vscode#276]
I don't always have Discord open while I'm developing in VSCode. If I open a window (or load a new project, or reload the window...) without Discord open, I get a notification saying "Couldn't connect to Discord via RPC: Error: Could not connect" that won't go away unless I click it.
![image](https://user-images.githubusercontent.com/816612/58350642-18b9c780-7e2c-11e9-90d5-6d09e2f2010f.png)

It would be nice to not have to do this any time I open VSCode without opening Discord first. If the Discord app isn't running, no connection should be attempted (or at least no error displayed).

**Comment by iCrawl** [comment]
I can't detect if discord is running or not based on the error message.
