### ISSUE TITLE
The discord-vscode dont detect discord in linux

### ISSUE THREAD

**Issue by DeamonPedro** [iCrawl/discord-vscode#295]
Discord 0.0.9 installed by AppImage
Visual Studio Code 1.35.0 installed by apt (repository)
Linux Deepin 15.10.1 (Debian based)

the extension does not detect the discord client, I already tried all discord versions, and I already tested a similar one, it also did not work, do you have any idea what might be happening?
ps: great extension, I use it in Win10 and I never had problems

**Comment by iCrawl** [comment]
https://github.com/iCrawl/discord-vscode/issues/77#issuecomment-411514866

**Comment by DeamonPedro** [comment]
Resolved]: Both the Discord and VScode must be installed by the distro repository, because Snap, Appimage, and Flatpak are not yet fully integrated into the system, causing problems with access to the Discord service.
@iCrawl thank you for your support!

**Comment by pandasoli** [comment]
> 
this is really strange since spotify does not need to be installed, perhaps this is given native integration
This is really weird, 'cause

**Comment by pandasoli** [comment]
> Resolved: Both the Discord and VScode must be installed by the distro repository, because Snap, Appimage, and Flatpak are not yet fully integrated into the system, causing problems with access to the Discord service. @iCrawl thank you for your support!

this is really strange since spotify does not need to be installed, perhaps this is given native integration
This is really weird, 'cause
