### ISSUE TITLE
[Request] Preference to disable Workspace name

### ISSUE THREAD

**Issue by EthanC** [iCrawl/discord-vscode#31]
As stated in [my last request](https://github.com/iCrawl/discord-vscode/issues/12), loving the Extension, keep up the great work! I've got a few more requests to make this Extension even better, I'll keep them in seperate Issues as they are all seperate features.

This Preference would be useful when you are working on a private/unannounced Project that you wouldn't want other users to see. Sort of niche, I know, but it'd be appreciated to have.

Note, setting the Workspace Name prefs to blank return an error
```
[icrawl.discord-vscode]4000 child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]

Error [RPC_CLIENT_ERROR]: 4000 child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]
```
so that is not a solution. You *can* paste in Non-Breaking Spaces, but that's not a very elegant solution, would be best to just get this preference.

**Comment by KingDGrizzle** [comment]
If you want just to be able to remove the workspace text from the state, this would be a good suggestion.

But if you just want to disable this extension for a specific workspace, you can do just that. Just open up the workspaces config.json and add `"discord.enabled": false`, and that should prevent it from showing again.

Either way, I'd love to be able to customize the whole `state` text to change it to things like `Working on {workspace}`, so this suggestion might be awesome in the long-run!

**Comment by KingDGrizzle** [comment]
Hey. It's me again.

I think what you want is `discord.lowerDetailsEditing` and `discord.lowerDetailsDebugging`, which you can overwrite to not include the `{workspace}` in them (per-workspace of course). So, you could have `Working on secrets` or whatnot.

Is that what you want? Or do you just want the state to be able to be empty? @EthanC

**Comment by EthanC** [comment]
Sorry about that, never seen the original reply to this.

Preferably I'd like to be able to just remove the line as a whole, while keeping the rest of the extension intact if that makes sense?

**Comment by KingDGrizzle** [comment]
Ah. You just want it to be empty. I'll...look into this

**Comment by KingDGrizzle** [comment]
@EthanC I think I did exactly what you want. Check #47
