### ISSUE TITLE
Selecting the Output tab shows "Editing extension-output#5"

### ISSUE THREAD

**Issue by justalemon** [iCrawl/discord-vscode#311]
Issue Type: <b>Bug</b>

When I select the `Output` tab, the RPC information changes to something that has nothing to do with the project.

![image](https://user-images.githubusercontent.com/11861253/60248737-45308b80-9891-11e9-80e5-56570bacd97b.png)

![image](https://user-images.githubusercontent.com/11861253/60248883-8b85ea80-9891-11e9-97de-2f79439df326.png)

Extension version: 3.6.0
VS Code version: Code - Insiders 1.36.0-insider (b7265738444f1eee05762341b4361ee6452a4154, 2019-06-27T05:22:06.378Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by iCrawl** [comment]
Should be fixed in v3.8.1
