### ISSUE TITLE
[Request] Preference to display "Line X of Y" or "File Size: Xyz"

### ISSUE THREAD

**Issue by EthanC** [iCrawl/discord-vscode#32]
Just as the title states. This could be a replacement for [my previous Request to disable Workspace Name](https://github.com/iCrawl/discord-vscode/issues/31).

**Examples:**
```
Visual Studio Code
Editing App.js
24:31 elapsed
Line 1,253 of 6,650
```
```
Visual Studio Code
Editing Payload.cpp
1:27 elapsed
File Size: 54kb
```

**Comment by KingDGrizzle** [comment]
So, good news, and bad news.

Good news first: You'll be able to get total lines and possibly size soon

Bad news: I cannot find a way to find the current line for the life of me. If you manage to find it, let me know.

**Comment by KingDGrizzle** [comment]
Heh, it's me again after what feels like an eternity. As I'm working on this as we speak, I found out that, indeed, you can get the 0-based current line! (of course we're going to add 1 to make it look pretty ~since we all know arrays start at 1~). So git --excited
