### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Casbas234** [iCrawl/discord-vscode#35]
I tryed a lot if things and stay without work, reloading, reinstalling etc. Help me

**Comment by KingDGrizzle** [comment]
You need to provide more info. What's your OS, Discord Version, the error, etc

**Comment by Casbas234** [comment]
Discord Version: Discord PTB 2.1.0. VS Code version: The newest The error: Rich prsence doesn´t work

**Comment by devdutchy** [comment]
> The error: Rich prsence doesn´t work

I doubt that's the actual error. If you could please provide the actual error, we can't do anything with just "it doesn't work"

**Comment by Casbas234** [comment]
It show's that im Playing VS Code but it only show the elpased time, no workspace, no project, and no logo

**Comment by KingDGrizzle** [comment]
Have you opened a file?

**Comment by Casbas234** [comment]
Of course!

**Comment by TheGreenCat** [comment]
Use "Open Folder" then select the file and it should work.

**Comment by Casbas234** [comment]
Thanks, it solved it
