### ISSUE TITLE
Couldn't connect to Discord via RPC: Error: Could not connect

### ISSUE THREAD

**Issue by SuperNeon4ik** [iCrawl/discord-vscode#354]
When I Discord Precense starting it throws an error: `Couldn't connect to Discord via RPC: Error: Could not connect` 
Console output: 
`Discord Presence activated!
Logging into RPC.
Encountered following error after trying to login:
Error: Could not connect
Logging into RPC.
Error: Could not connect`
Discord installed from .deb file
I was trying:
1. Reloading extension
2. Reloading discord
3. Redownloading discord
4. Redownloading extension
5. Write standart params
6. Write standart params to settings.json
7. Wiping discord
8. Run discord and vs-code using sudo

OS: Ubuntu 18.04
Discord: 0.0.9 with BetterDiscord(i was trying without)
Extension: icrawl.discord-vscode(3.8.1)

**Comment by iCrawl** [comment]
How'd you install vscode?

**Comment by SuperNeon4ik** [comment]
From Ubuntu Software

**Comment by resynth1943** [comment]
The version from the Ubuntu Software store is sandboxed. Install the .deb file from the link I shared earlier.

**Comment by SuperNeon4ik** [comment]
Yeah boiiiii! It's worked, I cloasing issue! Finaly, thanks @resynth1943

**Comment by resynth1943** [comment]
No problem! :tada:

**Comment by resynth1943** [comment]
Just remember that Discord and Visual Studio Code need to be installed either
  - from your package manager, which should be `apt` on Ubuntu systems
  - or from the `.deb` files on their respective websites.

If you expect this to work, you cannot use sandboxed versions of *either* program, not just Discord. I've heard this can be achieved in the Ubuntu Software Center by switching to the `community` install, but YMMV with this.

Anyway, I'm glad I could be of help, and I wish you all the best ;)

**Comment by SuperNeon4ik** [comment]
Thanks, I will

**Comment by kKerem** [comment]
Hey I have the same issue on MacOS Mojave 10.14.6

**Comment by Azzedine-zemmari** [comment]
@resynth1943 can u share with me the link to install the .deb file, please
