### ISSUE TITLE
Keep getting `Couldn't connect to Discord via RPC: Invalid Client ID` error

### ISSUE THREAD

**Issue by KidOfEpicness** [iCrawl/discord-vscode#41]
How do i fix this?

**Comment by KingDGrizzle** [comment]
Have you by chance changed the client ID from configs?

**Comment by KingDGrizzle** [comment]
Bump.

**Comment by KidOfEpicness** [comment]
Sorry, my email wasn't notifying me of this, it's fixed now, I just had to close all other Discord clients running on my PC.
