### ISSUE TITLE
Keep getting "Couldn't connect to Discord via RPC: Cannot read property 'image' of null" after update

### ISSUE THREAD

**Issue by MaxBosse** [iCrawl/discord-vscode#42]
Heyo,

it was working fine yesterday. Saw it updated and now everytime I try to connect to discord I get this error instead.

**Comment by KingDGrizzle** [comment]
Knew this was going to happen. Can you tell me the file extension that causes this?

**Comment by devdutchy** [comment]
You'll have to tell us more if you want us to be able to help. What error are you getting, what version of VSC, operating system, version of discord-vscode

**Comment by KingDGrizzle** [comment]
@devdutchy I know the cause of this. I just need the file extension to confirm it.

**Comment by devdutchy** [comment]
@KingDGrizzle alright

_Sent from my Galaxy J5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MaxBosse** [comment]
Hey,

I looked around and the issue seemed to be related to me having open a file of the extension ".ini" at the time I was connecting.

Switching to a supported file-type (like .cpp) during connecting works.

**Comment by KingDGrizzle** [comment]
Perfect. I'll quickly check and confirm this, then make a PR fixing it
