### ISSUE TITLE
"reconnect to discord"

### ISSUE THREAD

**Issue by Blaze135** [iCrawl/discord-vscode#430]
Issue Type: <b>Bug</b>

i tried click "reconnect to discord" and it said "comand 'discord.reconnect' not found" is there a way to fix it?

Extension version: 3.8.3
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (3.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by iCrawl** [comment]
This should be fixed in 3.9.4
