### ISSUE TITLE
The 3.9.1 version doesn't launch on VSCode

### ISSUE THREAD

**Issue by danivideda** [iCrawl/discord-vscode#440]
Issue Type: <b>bug</b>

When I launched VSCode (With discord already opened), my VSCode loads every extensions, except for the Discord Rich Presence. I don't see any indicator on left bottom side corner, where there usually a 'label' showing the Discord Rich Presence. 

However, when I installed the previous version (3.8.3), it worked just fine and it launched without any problem.

Extension version: 3.9.1
VS Code version: Code 1.39.2
OS version: Windows 10 x64

**Comment by iCrawl** [comment]
I can't reproduce this.

**Comment by danivideda** [comment]
I've tried to switch back to both 3.9.0 and 3.9.1, reload the vscode, and it's still not launching for me. When i install 3.8.3 again, it worked flawlessly without any problem.

Maybe it's only on my end then. My suspicion is maybe it has something to do with the Windows 10 Update that i just received last night(?) [because i had to reset my GRUB Bootloader and everything after this update], thoough it's really unlikely imo. But, that's pretty much it from what was changing / updated on my computer end.

At the end, it seems like it's only me that encountered this, so i think it's not gonna be a problem for anyone else. (And I'm still satisfied with 3.8.3 anyway, so.., thanks :D )

**Comment by iCrawl** [comment]
I made some pretty substantial changes in 3.9.4 now, if you could maybe test that, would be appreciated.

**Comment by danivideda** [comment]
Wow.
Yup, just updated to 3.9.4 and it worked perfectly.
You're fast. Thanks, it's worked fine now.
