### ISSUE TITLE
Could not connect - Ubuntu 17.10

### ISSUE THREAD

**Issue by inky-fox** [iCrawl/discord-vscode#45]
**Operating System:** Ubuntu 17.10
**Discord:** 0.0.4
**Visual Studio Code:** 1.20.0

**Error:** `Couldn't connect to Discord via RPC:`

I do not see any mentions making it non-compatible with Linux, and having used this on my Windows machine, it's a great tool to have. Unfortunately, it doesn't work on my laptop running Ubuntu 17.10 which is where I do the bulk of my code :frowning:

**Comment by FOG-Yamato** [comment]
Can you provide the console logs from your discord client aswell as on what user both processes run on?

**Comment by inky-fox** [comment]
Sure, no problem. The logs might be a *tad* long, I don't close Discord :sweat_smile:

**Discord log:** [discordapp.com-1518197527014.log](https://github.com/iCrawl/discord-vscode/files/1711883/discordapp.com-1518197527014.log)
*User**: Shane (only user on the system, root access)

**Comment by KingDGrizzle** [comment]
That's... odd... Maybe it's because it is ran under a snap and discord-rpc doesn't support those yet? Beats me.

**Comment by inky-fox** [comment]
Ah, possibly... It's weird because things like the latest Spotify update work fine. Though I suppose they're officially supported? That'd be my best guess.

Oh well, continue the awesome work either way! I'll close this issue for now :smile:
