### ISSUE TITLE
[Bug?] Potential Memory Leak upon Enabling/Disabling the Extension in VSCode while Spotify Rich Presence is active in Discord

### ISSUE THREAD

**Issue by EthanC** [iCrawl/discord-vscode#46]
I've not yet been able to confirm this, though this is the second time it has happened so I was curious if anyone else has experienced or can reproduce the issue?

Below are the actions I have taken each time this has happened:

- Open Task Manager (for monitoring RAM Usage)
- Open Discord
- Disable the VSCode Extension
- Reload VSCode
- Open Spotify, begin playing Music (make sure you have Spotify Rich Presence setup)
- Re-Enable the VSCode Extension
- Reload VSCode

If this repro works, VSCode will not re-open and your RAM usage will quickly jump to 100%, freezing your computer until you force shutdown. As stated, this is the second time this has happened to me. I'm not sure if this is a Bug on the Extension's end, Spotify's end, or Discord's end.

System Specs:

- Windows 10 (Latest Update)
- VSCode Stable Channel (Latest Update)
- Discord Canary (Latest Update)
- Spotify Desktop App (Latest Update)
- Discord-VSCode Extension (Latest Update)
- 12GB RAM

I frequently toggle this Extension off and on when I'd rather display my Spotify presence than VSCode Presence, which is why I've come across this issue. It'd be nice if there was a way to toggle the Extension's connection to Discord off and on without having to Reload VSCode each time.

**Comment by KingDGrizzle** [comment]
But you don't have to reload the window for it to stop.. also, that's weird. I'd test it but I cannot play spotify due to crappy country availability

**Comment by KingDGrizzle** [comment]
And minus my CPU wanting to commit suicide because of VSCode, I was unable to reproduce this after 2 attempts..
