### ISSUE TITLE
TypeScript Icon looks different - Enhancement

### ISSUE THREAD

**Issue by elias-knodel** [iCrawl/discord-vscode#478]
## Description of the problem and the solution i'd like:
As you can see in the pictures, the TypeScript icon looks somehow small and it would be cool if it would look something like the JavaScript Icon

## Additional context:
Here are some screenshots of the presence icons as they are now:

![image](https://user-images.githubusercontent.com/42189915/69466839-f7f40f80-0d85-11ea-8471-00a948d80036.png)

![image](https://user-images.githubusercontent.com/42189915/69466858-06422b80-0d86-11ea-80a4-55fa9c14768f.png)

## My solution:
I made the TS icon which looks better in my opinion. I attatched it here: 

![image](https://user-images.githubusercontent.com/42189915/69467704-84540180-0d89-11ea-8f5e-8209e3bd0f81.png)

### PS:
I know it's a personal preference but please consider the icon change ;D

**Comment by iCrawl** [comment]
With the TypeScript rebranding I wanna stick as close to their original as possible: #658
