### ISSUE TITLE
Not sure how to use?

### ISSUE THREAD

**Issue by WiftedMC** [iCrawl/discord-vscode#5]
Could you explain how to install and set-up more in the README.md because I am really confused on how to install.

**Comment by iCrawl** [comment]
I'm not exactly sure where you get confused.
All you have to do is install it and have a discord client running.

**Comment by WiftedMC** [comment]
I did both of those and it isn't working.

**Comment by iCrawl** [comment]
Make sure you enabled the option in discord to display your playing game. Other than that, there's not much more you can do.
