### ISSUE TITLE
Option to hide workspace when no workspace found

### ISSUE THREAD

**Issue by Gobluebro** [iCrawl/discord-vscode#50]
I cannot get `"{null}"` working for `discord.lowerDetailsNotFound`. Is it possible to add the ability to not show the workspace that to that property? I saw some of the previous closed issues which include it for other properties. I just want an empty line if there is no workspace found.

**Comment by KingDGrizzle** [comment]
That's because `lowerDetailsNotFound` gets replaced by `{workspace}`. I'll look into adding the possibility for `{null}` to get replaced there too.

**Comment by Gobluebro** [comment]
That would be awesome thank you @KingDGrizzle
