### ISSUE TITLE
Idling counter resets after 15 seconds

### ISSUE THREAD

**Issue by DoNotSpamPls** [iCrawl/discord-vscode#51]
Example shown here: 
![](https://bitcoin.is-serious.business/2a2202.gif)

**Comment by smt923** [comment]
+1 happens for me too

Latest (?) discord, windows 10, vscode 1.22.1, and only happens on idling, every other counter/timer works fine

**Comment by KingDGrizzle** [comment]
We should probably not have a timer when you're idle. But looks like a weird bug 😞

**Comment by Hazmi35** [comment]
+1
This issue happen to me too
and Rich Presence missing after 1 hours :/
