### ISSUE TITLE
Q: Is it possible to use this without installing the discord app 

### ISSUE THREAD

**Issue by cswl** [iCrawl/discord-vscode#52]
I use discord from the browser..

**Comment by bananaboy21** [comment]
You do realize that even normal presence won't work on discord in browsers. Any sort of playing status only works on a PC DiscordApp client.

**Comment by KingDGrizzle** [comment]
No. While you can install the extension, it'll be useless if you don't have a Discord app installed and launched.

**Comment by cswl** [comment]
I guess.. the only way is to reverse enginneer the Rich Presence client code that discord has on the app..
