### ISSUE TITLE
Couldn't connect to Discord via RPC: Invalid Client ID

### ISSUE THREAD

**Issue by SaiyanShivvy** [iCrawl/discord-vscode#53]
I keep getting this error whenever I try connecting to discord.

**Comment by LumiteDubbz** [comment]
Well is "383226320970055681" your client ID? Go into your <b>Discord<b> settings, appearance, enable developer mode, send a message, right click on your username above that message, copy ID and replace "383226320970055681" with whatever you copied.

**Comment by KingDGrizzle** [comment]
You are not supposed to change the client ID unless you REALLY know what you're doing. The client ID is NOT your user ID, but rather the Discord "Application" (from their dev site) which has all the required assets .

**Comment by SaiyanShivvy** [comment]
After doing a reinstall, it seems to work now. Not sure why it wasn't working before.
