### ISSUE TITLE
Two Discord clients running, one shows rpc other doesnt

### ISSUE THREAD

**Issue by AliSyedHammad** [iCrawl/discord-vscode#549]
Hi, so for a reason, I have to run two discord clients at once on my PC. The problem with that is that it works as intended on one client, but doesn't show rpc on the other client. Is there a way to make it work with both clients or maybe specify which client i want it to work with?

Thanks

**Comment by iCrawl** [comment]
No plans to implement that. You can somewhat make it work by starting the client you want it to display first and then the other one after its hooked.
