### ISSUE TITLE
[Request] Posibility to show the git project

### ISSUE THREAD

**Issue by yadkee** [iCrawl/discord-vscode#55]
Just as it sounds. I would love a config option that shows the folder that contains both the file and the .git project.

> **Visual Studio Code**
> Editing main.py
> Project Chess

**Comment by EnriqCG** [comment]
Might as well include the link to the corresponding git repository.

**Comment by KingDGrizzle** [comment]
Linking seems rather pointless since (from what I know anyways), RPC doesn't have hyperlinks and showing that long URL won't be that good.

As for showing the repository name... Sure? I don't know if it'll be feasible, since you can get the current workspace name, but it is probably doable

**Comment by Yadkee** [comment]
I think that some of us have multiple git projects in the same workspace and it would be cool to have the option to show which one are we working in.

**Comment by KingDGrizzle** [comment]
Back again, bringing some... news? Anyways:

vscode considers workspaces the root folder that hosts your files. (If my project folder is named `Creative Name`, the workspace name is `Creative Name` (also current behaviour of `{workspace}`)).

Now... That bases off the root folder name. While your repository might have another name, I _really_ don't know at this point in time if we can get your repository name from any `.git/` files. (if you know, let us know!)

But hey, never gonna give up!

**Comment by EnriqCG** [comment]
Yep, you can get the repository name through `.git` files.

In the file `.git/config` in section `[remote "origin"]` the repository url is provided.

![.git/config image](https://user-images.githubusercontent.com/38569176/39493884-b1b23874-4d94-11e8-8ae4-bfd2995ba2fe.png)

There is extra information such as what branches are available. (not sure how to get current branch info although that would be nice).
