### ISSUE TITLE
Can't connect to discord

### ISSUE THREAD

**Issue by lewiswulski** [iCrawl/discord-vscode#560]
Hello, I can't seem to get it to display on my discord anymore.
I am using Windows 10 version 1903

I have tried reinstalling the program

I have had no luck.

Hope someone can help

**Comment by O5X** [comment]
I'm having this issue as well!

**Comment by lewiswulski** [comment]
Hmm well, I fixed it... Just start discord as admin then run visual studio as an admin

**Comment by O5X** [comment]
That doesn't seem intended, can you reopen until Icrawl or another dev can confirm?

**Comment by iCrawl** [comment]
There is no such thing to confirm this, look at the other similar issues to this.

If you can't connect to discord, you or I can't do anything against it. Its not a limitation or bug in this library, its on discord.

**Comment by O5X** [comment]
Is there nothing you can do to help then? I'm sort of out of ideas on what to try haha

**Comment by iCrawl** [comment]
I just said it, there is nothing *anyone* can do.

I wouldn't be surprised if it randomly after a few restarts or something starts to work. There isn't really any kind of logic behind this.
It's trying to connect to the RPC server of your discord client, if it fails, it fails. There isn't much that can be done.

**Comment by O5X** [comment]
Yea. I guess I'll try some other stuff to see if I can get it working. Thanks anyway!
