### ISSUE TITLE
Support for Jupyter Notebook

### ISSUE THREAD

**Issue by Jetpuffed** [iCrawl/discord-vscode#561]
![1200px-Jupyter_logo](https://user-images.githubusercontent.com/41945762/78704431-b1302d80-78c0-11ea-868c-de635a3f9305.png)

**Comment by TennessineGD** [comment]
I can indeed confirm that Jupyter Notebook files are supported when purely text based, however they seem to show up as "Idling" the moment the advanced UI shows up, making it basically useless.
