### ISSUE TITLE
Discord Presence taking priority over all other activities

### ISSUE THREAD

**Issue by tahnik** [iCrawl/discord-vscode#570]
When this extension is installed, discord does not show any other activities. For examples, if I have my vscode open and I am playing a game, discord will keep showing that I am playing visual studio code. Is there a way to prioritise everything else over Discord Presence?

**Comment by iCrawl** [comment]
The last initialized presence takes priority. But that also might depends on whos viewing the presence itself.

There is not a way to fix this or change the priority.
