### ISSUE TITLE
Seems like the extension can't connect with Discord beta version

### ISSUE THREAD

**Issue by puchijon** [iCrawl/discord-vscode#575]
Since I installed "DiscordPtb", VSCode give me the error "Couldn't connect to Discord via RPC"

**Comment by iCrawl** [comment]
Please check the readme

https://github.com/iCrawl/discord-vscode#cant-connect-to-discord-check-those

If neither of those things help, theres nothing you can do or I can do.
This has nothing to do with Discord Beta or Canary (I personally use Discord Canary on Windows 10)
