### ISSUE TITLE
Please add .ipynb file support

### ISSUE THREAD

**Issue by cahyoardhi** [iCrawl/discord-vscode#576]
thank you to create this awesome file extension :)
but if you can add .ipynb (python jupyter notebook support) it will be more helpfull for us who using .ipynb file to write python code

![image](https://user-images.githubusercontent.com/47904651/80958011-de77e900-8e36-11ea-804d-af77119c97e1.png)

thanks

**Comment by dwarf-rbi** [comment]
Was just about to write the same :)

**Comment by vaine4** [comment]
Up same here :D

**Comment by Zenoix** [comment]
I agree

**Comment by Acher224** [comment]
There is code but it doesn't work, this is a bug

**Comment by zkgz** [comment]
Maybe it has something to do with the python extension. Because the python extension opens a new .ipynb file (not the original .ipynb file when you open them)

**Comment by zeina99** [comment]
+1

**Comment by jbofill10** [comment]
I've noticed that before the python extension is able to convert the .ipynb content into cells and such that is more easily interpreted by the user, the extension will detect that we are working in a ipynb file, but once the python extension renders the cells and everything, the extension says it's idling

**Comment by Youngermaster** [comment]
I don't know why it was closed by @cahyoardhi, although the problem is still over there.

Screenshot: 
![image](https://user-images.githubusercontent.com/36933318/124523967-c4c98d00-ddbe-11eb-8ff6-a8344336a60e.png)

I don't know if someone fixed it.
