### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by KurokuTetsuya** [iCrawl/discord-vscode#577]
Can I set elapsed time as project opened elapsed instead file opened elapsed?

**Comment by Hazmi35** [comment]
You can, VSCode Settings > Extensions > Discord Presence Configuration > Workspace Elapsed Time, and check the checkbox, or you set `"discord.workspaceElapsedTime": true`, directly into your VSCode settings.json

**Comment by KurokuTetsuya** [comment]
OwO, thanks
