### ISSUE TITLE
Godot Support Needed

### ISSUE THREAD

**Issue by Airbus5717** [iCrawl/discord-vscode#581]
![godoticon](https://user-images.githubusercontent.com/55999379/81499306-57fa5600-92d3-11ea-9e5f-47dbbde8f51c.png)
logo ^
Free open source game engine 
uses GDScript as a programming language https://godotengine.org/
File Extension : .gd 

Forked repo https://github.com/Airbus5717/discord-vscode
only the icon added

**Comment by seanputera** [comment]
Thank you for this!

**Comment by iCrawl** [comment]
Added in 3.15.0
