### ISSUE TITLE
Ability to flip Big and Small Image.

### ISSUE THREAD

**Issue by legoatoom** [iCrawl/discord-vscode#584]
In the plugin the big imagine is always the language, and the small image is Visual Studio.
There is currently, as far as I know, no way to flip them to have Visual Studio Code as the big image.

**Comment by iCrawl** [comment]
I don't see why this should be a thing in the first place. What does it matter which editor you really use?

I don't think that should be the predominant display here.

**Comment by legoatoom** [comment]
I can understand your reasoning behind this, but I would like to tell you that it is very common during programming that you as the programmer do not understand why a feature is wanted.

Not to sound rude, but I prefer seeing the editor as the predominant.
This is already possible in the JetBrain Variant of this Plugin:
![afbeelding](https://user-images.githubusercontent.com/16699025/82567848-40965500-9b7e-11ea-919d-32d1745b1d50.png)

**Comment by iCrawl** [comment]
This has nothing to do with me not understanding but more a proper reasoning why it should be.

Not to sound rude or anything.

**Comment by legoatoom** [comment]
The reason is that I actually find it looks better this way.
Having the main program displayed and the language as bonus info.

**Comment by iCrawl** [comment]
Yeah I currently don't know if this will be a thing in the foreseeable future.
This is more than just a `swap` here. The icons itself were not designed to be displayed on such a tinier space.
For most of them it would look very ugly and I'm not really into making that compromise. Theyd have to look good on both dispays.

**Comment by legoatoom** [comment]
That is fine. I don't mind having to wait.
And I would not advise spending time doing it if it wasn't a highly requested feature.

**Comment by iiLeafy** [comment]
It would be a cool feature, but it's really useless atleast for me, any yeah what he said is true if it's not highly requested, then there's no point in implementing that feature.

**Comment by iCrawl** [comment]
Added in v5.1.0, it's a setting in the Extension settings. Defaults to false.
