### ISSUE TITLE
Setting to stop "Couldn't connet to discord via RPC"

### ISSUE THREAD

**Issue by Glitchii** [iCrawl/discord-vscode#596]
I work in Windows subsystem for linux in VSCode sometimes. When I open VSCode I keep getting that error. It's because I'm in the WSL mode I assume. And I currectly don't care that much if it doesn't connect for that time and find it annoying that that pops up all time. Add a setting to disable it temporarily? 
![image](https://user-images.githubusercontent.com/46096865/84580939-03fff700-add4-11ea-84be-55cb8f05aad8.png)

**Comment by sleepyArpan** [comment]
Hey, have you had a look at issue #85 ? I think that should solve your connection problem. Also I have seen that the extension only kicks in if you have discord running in the background.
