### ISSUE TITLE
The extension is not working while I'm running the vs code in admin/without admin!

### ISSUE THREAD

**Issue by XynoxTheDev** [iCrawl/discord-vscode#597]
- Issue Type: `Bug`
- Extension Name: `discord-vscode`
- Extension Version: `3.14.0`
- OS Version: `Windows_NT x64 6.2.9200`
- VSCode version: `1.46.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by BopItFreak** [comment]
I'm having the same sort of issue. It says "Connected to Discord" but I don't see anything in my status. In fact, my other discord-rpc applications don't work either. I think this is a problem with the discord-rpc package.

**Comment by XynoxTheDev** [comment]
> I'm having the same sort of issue. It says "Connected to Discord" but I don't see anything in my status. In fact, my other discord-rpc applications don't work either. I think this is a problem with the discord-rpc package.

Yeah, the same issue is been faced by me also. Guys do solve this issue asap!

**Comment by Ben-VP** [comment]
Yeah, I am also having this issue. Was working fine yesterday.

**Comment by SWEDCODER** [comment]
Why did you close this ? have you found a solution ?

**Comment by MorganCaron** [comment]
In discord, make sure that game activity is enabled and that Visual Studio Code is detected as a game (add it manually if it does not appear automatically).

If you don't have the Discord Presence extension on VSCode, Discord will just display that you are on VSCode (without further details).
If you have the extension installed, Discord will display your activity details (file being edited, editing time, etc).

I was in the same situation as you. It worked for me.

**Comment by XynoxTheDev** [comment]
> Why did you close this ? have you found a solution ?

Yes!
