### ISSUE TITLE
Please publish the extension to Open VSX

### ISSUE THREAD

**Issue by chaNcharge** [iCrawl/discord-vscode#598]
I'm a [VSCodium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VSCode, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the Discord Presence extension to the [open-vsx.org](https://open-vsx.org/) marketplace as it is unclear if it's legal to use the official Microsoft extension marketplace on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional information on how to publish an extension to Open VSX can be obtained [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by iCrawl** [comment]
Didn't even know this was a thing 👍 

https://open-vsx.org/extension/icrawl/discord-vscode
