### ISSUE TITLE
What's the default image key if asset not created? 

### ISSUE THREAD

**Issue by fourjr** [iCrawl/discord-vscode#6]
I'm reading the code from https://github.com/iCrawl/discord-vscode/blob/master/src/extension.ts#L147 and was wondering what is the default key name if the file ext asset is not found (for large image)

**Comment by iCrawl** [comment]
No such thing yet.

**Comment by fourjr** [comment]
hmm, could you make it `vscode-big` or something? that'd be very much appreciated! thank you :)

**Comment by iCrawl** [comment]
I added better language detection now, if no file ext is found it will fallback to `txt`

**Comment by fourjr** [comment]
okay thanks :)
