### ISSUE TITLE
Couldn't connect to Discord via RPC: Error [RPC_CONNECTION_TIMEOUT]

### ISSUE THREAD

**Issue by MGRich** [iCrawl/discord-vscode#61]
Started to happen a while back (a month ago). My Windows 10 PC hasn't done any updates before and since then. I never have anything with Rich Presence open at the time, either.

**Comment by iCrawl** [comment]
Nothing much I can do about, this is an issue (if at all) with the underlying library.

**Comment by Tachi107** [comment]
Having the same issue here. Worked fine till yesterday, but now every time I open a folder I get the error `Couldn't connect to Discord via RPC: Error: RPC_CONNECTION_TIMEOUT`, and I have no idea why it happens, since nothing changed since yesterday on my computer.

Using both Discord and VSCode downloaded from their site on Debian Bullseye

**Comment by checkraisefold** [comment]
same issue here

**Comment by AryaveerSR** [comment]
same here :P

**Comment by Jeremiah0604** [comment]
same issue

**Comment by MerrickKing** [comment]
Still having this issue

**Comment by ala8** [comment]
same problem here

**Comment by dhaulathu** [comment]
im having this issue too, running with admin privilidges doesn't change anything

**Comment by kratosrog** [comment]
everything was working perfectly fine but i had to reinstall os and every stuff now facing this exact issue tried to connect multiple times restarted both vs code and discord but getting same error again and again.

**Comment by cdwcgt** [comment]
I have this problem, and I recover it by re-enabled the plugin

**Comment by Gaming32** [comment]
Same problem

**Comment by aidan959** [comment]
Also worth checking that  you dont have rich presence disabled in vscode:
![image](https://github.com/iCrawl/discord-vscode/assets/6438565/426ad250-74d2-49ab-b6bc-30fb2eefa65a)

sorry to necro
