### ISSUE TITLE
{gitreponame} doesn't work

### ISSUE THREAD

**Issue by shardeex** [iCrawl/discord-vscode#616]
Hello, I have tried to use this:
![image](https://user-images.githubusercontent.com/54213170/87167826-3f5beb80-c2d6-11ea-8524-6015a68b2fb8.png)
And unexpectedly got it:
![image](https://user-images.githubusercontent.com/54213170/87167779-2bb08500-c2d6-11ea-86ed-d1be158a4c68.png)
So, extension defines the current branch (master), but not the repository. I tried to reinstall, but that did not help.
Maybe this is because it is not my repository? (however, I am its contributor)

**Comment by iCrawl** [comment]
This should be fixed in the latest release.
