### ISSUE TITLE
Doesn't connect to Discord RPC

### ISSUE THREAD

**Issue by Lemming8** [iCrawl/discord-vscode#621]
Out of nothing, the extensions stopped working and instead displayed the error "Couldn't connect to Discord RPC". Even after resetting the settings and reinserting my Userid, it didn't work. I also tried reinstalling the extension and restarting vscode, discord and my PC.

**Comment by iCrawl** [comment]
> reinserting my Userid

You aren't even supposed to insert your user Id in the first place.

**Comment by Lemming8** [comment]
didn't know that, sry :/
fixed the problem
