### ISSUE TITLE
Adding support for another language, GSC.

### ISSUE THREAD

**Issue by mikzyy** [iCrawl/discord-vscode#623]
GSC is a language for Call of Duty games. It's used across various of the games and I know lots of people who use VS Code and the Discord Presence and it would be cool if it had a presence for it. Its used across lots of COD games and there are communities out there for scripting and making mods (friendly ones, not cheating ones) with this language. Not a top priority but would be cool.

**Comment by ahtee** [comment]
The language is just called __gsc__?

in src/data/languages i could add that, what sort of file extensions does gsc acknowledge?

**Comment by mikzyy** [comment]
.gsc, correct
