### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by sotpurk** [iCrawl/discord-vscode#624]
Although, reinstalling the extension works for a while, but the issue presents itself randomly both when discord is/is not running. 
No extension starts up until I either disable or uninstall this extension. 
I'm on VSCode-Insiders. 
Let me know if you need the logs and it'd be great if you could also specify the location of the said logs. 
Thank you.

**Comment by iCrawl** [comment]
It could be that it conflicts with another extension.

I can't seem to reproduce this with my extensions, or all of mine disabled and only this one enabled.

**Comment by sotpurk** [comment]
After the last update, it seems like the issue is now somehow resolved. I have no clue about what the underlying issue was or how it's working now. But anyway, thanks for your help. I'll close this.
