### ISSUE TITLE
Rich Presence Images Missing

### ISSUE THREAD

**Issue by EthanC** [iCrawl/discord-vscode#63]
Just noticed this today. Fresh installing the Extension and restarting Discord does not solve the issue.

- Latest Discord (Canary)
- Latest VSCode + Extension (Stable)
- Latest Win10 x64

![image](https://user-images.githubusercontent.com/16727756/39792964-ec30abb0-5308-11e8-975b-651b32214abd.png)

EDIT: This may be due to API Issues. Will close the issue if that's the case.

**Comment by iCrawl** [comment]
That's an issue with the latest Discord Canary update, none of the Rich Presences besides Spotify work correctly.
