### ISSUE TITLE
"remove ability to edit client id" why?

### ISSUE THREAD

**Issue by iwa** [iCrawl/discord-vscode#631]
is it a real huge problem that people can use their own discord application?

**Comment by iCrawl** [comment]
No, but pretty much everyone thought they had to input their user id instead.
It was too much of a hassle to let it be editable. Even the warning that they should not edit it except their "know what they are doing" didn't help.

If you really want to use your own application you can fork it and change it, then do `vsce pack` and just install the packed version without having to publish one on your own.

**Comment by iwa** [comment]
ah i see
thanks for the advice, will do!

**Comment by ungive** [comment]
Maybe renaming the setting to "Discord application ID" would help? I was surprised to not find a setting to change it. I can see how "client ID" would be misleading, but "Discord application ID" should be pretty definitive. What do you think?
