### ISSUE TITLE
TypeScript rebranding

### ISSUE THREAD

**Issue by pizzafox** [iCrawl/discord-vscode#658]
[TypeScript recently rebranded](https://www.typescriptlang.org/branding) and they have a few different logos for different display resolutions. The smaller the display resolution is the less padding there is.

![TypeScript logo grouping](https://www.typescriptlang.org/images/branding/logo-grouping.svg)

[Their asset pack](https://www.typescriptlang.org/branding/typescript-design-assets.zip) includes a 128px SVG logo which is closest to the 60px and 90px Discord displays the large image as:

![60px](https://i.imgur.com/So8pqSE.png)
![90px](https://i.imgur.com/BOEjrqb.png)

Here is the 128px SVG from their asset pack exported to 1024px (recommended for Discord) in GIMP (RGB color 8-bit gamma integer, GIMP built-in sRGB)
![128px TypeScript logo SVG exported to 1024px](https://i.imgur.com/GgtCnwd.png)

**Comment by iCrawl** [comment]
Updated 👍
