### ISSUE TITLE
Couldn't connect to Discord via RPC: [object Object]

### ISSUE THREAD

**Issue by Geekz45679** [iCrawl/discord-vscode#66]
**I keep getting this error:**
![VSCode Error](https://user-images.githubusercontent.com/22227801/39963654-94b3cbf0-56b5-11e8-94cf-3c016d76fa5f.png)

**Here are my software specs:**
VSCode:
![VSCode Version Info](https://user-images.githubusercontent.com/22227801/39963660-bc0f1a88-56b5-11e8-9fb5-e953c18c8f51.png)

Discord Canary: 
![Discord Canary Version Info](https://user-images.githubusercontent.com/22227801/39963692-673c7eb4-56b6-11e8-9092-c002548bafc1.png)

Operating System (Mac OS):
![screen shot 2018-05-13 at 2 04 09 pm](https://user-images.githubusercontent.com/22227801/39963698-87868f0c-56b6-11e8-9c74-64134c4b4549.png)

**Comment by HunterWilson56** [comment]
getting the same problem

**Comment by w0298i** [comment]
same

**Comment by Geekz45679** [comment]
Is this issue dead? The lack of attention this is getting is a little bit ridiculous.

**Comment by iCrawl** [comment]
Looking through various of other issues of that kind should have gotten you that answer pretty quickly, namely:

https://github.com/iCrawl/discord-vscode/issues/61
https://github.com/iCrawl/discord-vscode/issues/54
https://github.com/iCrawl/discord-vscode/issues/49
https://github.com/iCrawl/discord-vscode/issues/21
https://github.com/iCrawl/discord-vscode/issues/9
https://github.com/iCrawl/discord-vscode/issues/8

I'm just kind of sick of people not looking through past issues at this point, so I left this one open.

**Comment by spkane** [comment]
It might help folks if the error message including a link to a troubleshooting doc or something, that had a few suggestions. Most of the "answers" in all of these issues, are very vague and don't have any follow through on possible root causes.

**Comment by SherloxFR** [comment]
@iCrawl (Adding a pointer in your README to this might be be helpful).

I am using Ubuntu 18.10, and installed both Discord and VSCode using snap.

Snap was the origin of my `Can't connect to Discord`, as it sandboxes apps.
It has been confirmed by a Discord collaborator: https://github.com/discordapp/discord-rpc/issues/213#issuecomment-410776934

So if you installed any of those two using Snap, here's the fix:
- `sudo snap remove vscode discord`
- download the `.deb` files from the official websites
- install the `.deb` files using the `sudo dpkg -i package.dpkg` command
- DO NOT USE UBUNTU SOFTWARE CENTER, AS IT USES SNAP.

**Comment by EdwinArevalo** [comment]
Thank you very much, it also works on ubuntu 20.04 LTS

**Comment by Luann0233** [comment]
@SherloxTV Thank you S2

**Comment by GabrielMessiasdaRosa** [comment]
You save the day, thx
