### ISSUE TITLE
[Feature Request] Ability to customize what to be show

### ISSUE THREAD

**Issue by felixfong227** [iCrawl/discord-vscode#69]
In most cases, it a-okay to show all the information that is related to the current project I'm working on, but sometimes I might switch to some project is more likely to be a closed source project, but I still want to ability to tell someone that I'm actually paying my hard work and dedication to the project, a good way to do so is via this lovely VSCode plugin and all I want is to eliminate some of the more sensitive information like the file name

**Comment by KingDGrizzle** [comment]
You... can already do that tho... Go in your preferences, search for discord, and scroll down. There are so many options you can do.

**Comment by felixfong227** [comment]
Thanks for the quick reply @KingDGrizzle lmao I should take a look at the settings.json before I post dis issue lul

**Comment by KingDGrizzle** [comment]
It's all good. 😄
