### ISSUE TITLE
Option to default to disabled on new workspaces

### ISSUE THREAD

**Issue by Maselkov** [iCrawl/discord-vscode#7]
Hey, great work. For privacy reasons, I think it would be great to have an option to have rich presence be disabled by default on new workspaces, unless you explicitly enable it for them.

**Comment by iCrawl** [comment]
Hmm. This is indeed a valid concern.

I'm not quite sure how to painlessly solve this though. Opt-in to have the presence displayed is kinda not the way I want to go.

**Comment by iCrawl** [comment]
Okay so @Maselkov 

What you can do is: 
- In your global `settings.json` set `discord.enabled: false`
- In your local `settings.json` set `discord.enabled: true`

This way you have full control over what you want to show and its deactivated by default on new workspaces, does this satisfy what you asked for?

**Comment by Maselkov** [comment]
Yes this is perfect, thank you!
