### ISSUE TITLE
No Discord Client Detected

### ISSUE THREAD

**Issue by EthanC** [iCrawl/discord-vscode#73]
- Windows 10 x64 1803 17134.112
- Visual Studio Code 1.24.1
- Discord Canary Build 18051

![image](https://user-images.githubusercontent.com/16727756/42130334-a948efd8-7ca7-11e8-8880-1a541121d5f4.png)

This issue has persisted for 4 days now (since Wednesday, June 27th). I've open/closed Discord & VSCode, Reinstalled the Extension, Disable/Enabled the Extension, Restarted Windows, and Cleared all temporary files, to no avail.

Pressing the Reconnect to Discord button produces the following notifications...

![image](https://user-images.githubusercontent.com/16727756/42130347-34abe666-7ca8-11e8-894c-f615a6336963.png)

Any help would be appreciated.

**Comment by iCrawl** [comment]
I updated the RPC package, since a lot of people seemed to have issues connecting to RPC in the last few days, can you try again and tell me if this fixed it?

**Comment by EthanC** [comment]
Hmm, so it is working now. However, when initially opening VSCode it still errors out, it only begins to work after I open a workspace and new file (rather than the untitled file from startup).

Discord Presence: 2.6.1

**Comment by EthanC** [comment]
Still an issue after the latest release.

**Comment by EthanC** [comment]
@iCrawl any update?

**Comment by iCrawl** [comment]
Not really, this seems to be quite inconsistent. It never happens to me or anyone I know specifically.
Its most likely a problem with the underlying lib I'm using to connect to RPC with Discord or even Discord itself.
