### ISSUE TITLE
Could not Connect to Discord via RPC

### ISSUE THREAD

**Issue by codepupper** [iCrawl/discord-vscode#78]
Ever since yesterday the Plugin won't work on my Windows PC. I've tried adding VSC using the Games tab but that won't work either. 

Here's the error I get
https://e-six-two.one/u/Joint-Stegosaurus-1.png

**Comment by smt287** [comment]
This problem happened to me. The solution is as follows:
If you are running Discord as an administrator, you must close it in the program settings.
Ex: [https://i.hizliresim.com/NDoXkN.png](url)

**Comment by TheLastZombie** [comment]
What if not? [I'm getting a similar (probably the same) error](https://user-images.githubusercontent.com/8181990/49339230-220d6880-f62f-11e8-846a-bf30ae549c9f.png) (not running anything as admin), using Windows 10 (1803), the latest stable Discord version and the following VS Code specs:

```
Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
