### ISSUE TITLE
'No Discord Client detected!' even when Discord is open.

### ISSUE THREAD

**Issue by MikeModder** [iCrawl/discord-vscode#8]
I've tried reinstalling this extension, but every time on startup it says that there is no client detected. I've added VS Code as a game in Discord and ensured that the option to display the running game is on.

Is there anything else I should try? Here's a screenshot showing the error with the Discord client next to it.
https://vgy.me/jHLrCE.png

**Comment by iCrawl** [comment]
Can you tell me your vscode version `Help -> About` and Discord branch? Stable, PTB, Canary?

**Comment by MikeModder** [comment]
Yep. VS Code is version 1.18.1 and I'm using the Stable branch for Discord.

**Comment by iCrawl** [comment]
Interesting.

Can you try restarting Discord while VS Code is closed and then reopen VS Code?
If that doesn't work, try manually enabling the extension via the command palette `F1 -> Discord Presence enable`

**Comment by MikeModder** [comment]
Here's what I did `Close VS Code and Discord -> Open Discord -> Open VS Code`. It still shows the error.
Toggling it form the Command Palette didn't have any effect.

**Comment by iCrawl** [comment]
I'm not entirely sure where I should start debugging this.

No matter if I use Insiders or Stable, and Stable, PTB or Canary Discord, it connects fine for me except when I do not have an internet connection.

I assume this is latest Win10?

**Comment by MikeModder** [comment]
No, I'm using Windows 8.1.

**Comment by iCrawl** [comment]
Can you try running the example over in this repo https://github.com/devsnek/discord-rpc and tell me how it goes?
