### ISSUE TITLE
Files with the .sp extension are SourcePawn files

### ISSUE THREAD

**Issue by strafe** [iCrawl/discord-vscode#843]
`.sp` was added as an additional extension to the existing PAWN language type in a previous commit. `.sp` files are exclusively used by the SourcePawn language (a fork of PAWN).

Would it be possible to use the same icon, but instead of `Editing a PAWN file`, it read `Editing a SourcePawn file`. If not we can come up with an altered icon since the language doesn't really have one.

`.inc` files are shared by both languages and choosing which language they should appear as is probably divisive.

**Comment by iCrawl** [comment]
Feel free to come up with a new logo or something, but there is no way for me to modify what VSCode tells me what the name of those files is.

**Comment by strafe** [comment]
> Feel free to come up with a new logo or something, but there is no way for me to modify what VSCode tells me what the name of those files is.

@iCrawl this doesn't seem right... I had a peek at the `resolveFileIcon` function and it's clear that the `PAWN` string in `Editing a PAWN file` is coming from `languages.json`.

I'd send a PR to change the language name but I imagine you'd need to upload a new asset to Discord first?
https://github.com/iCrawl/discord-vscode/blob/4503a1d5ed93c0766f1be497ccdd59455b2a56f5/src/util.ts#L40-L63

**Comment by iCrawl** [comment]
Right, I forgot about that special handling.

Certain languages are built-in VSCode detected, those fall under the "known languages" category, those usually only contain languages that are natively supported by VSCode, others are dynamically created you are correct.

Yes, in the PR you would tell me which image to use for it.

I was confusing this with a different request I got too, which included 2 languages sharing the same extensions, which makes it rather hard to pick and choose.
