### ISSUE TITLE
New update broke it.

### ISSUE THREAD

**Issue by callumok2004** [iCrawl/discord-vscode#892]
![image](https://user-images.githubusercontent.com/35779365/107552703-c3a78180-6bcb-11eb-9f49-dd3719c38a3b.png)

**Comment by iCrawl** [comment]
Yes, read the settings page again. The strings are different now for the replace.

**Comment by sportshead** [comment]
> Yes, read the settings page again. The strings are different now for the replace.
@iCrawl if there is a breaking change that causes the rich presence to stop working, one of these should have happened:
- the major version should have been increased
- the user should have been notified somehow
- support for the old strings should be kept and only removed in the next major version
- the strings should be automatically converted to the new strings

**Comment by iCrawl** [comment]
> One of these should have happened

Exactly one of the following did happen, the major version was increased.
