### ISSUE TITLE
Time elapsed

### ISSUE THREAD

**Issue by Milo123459** [iCrawl/discord-vscode#894]
Is there an option that changes the elapsed time whenever you open a file?

**Comment by iCrawl** [comment]
I removed that in v5, I may reintroduce it later. But most people wanted to have it always count and not per file change.

**Comment by Milo123459** [comment]
Are you happy for a PR covering it?

**Comment by Ashesh3** [comment]
is there a way to completely disable elapsed time? and just have the rich presence without elapsed time?

**Comment by iCrawl** [comment]
@Ashesh3 You can now do this in 5.4.0
