### ISSUE TITLE
Can't connect to discord via RPC

### ISSUE THREAD

**Issue by VulgarBear** [iCrawl/discord-vscode#9]
I've been getting this error and can't seem to locate a source. I'm running VS Code v1.17.2 on the latest build of Windows 10. Not sure if it matters but I do have PFSense handling my routing.

> Couldn't connect to discord via rpc: connect EPERM \\?\pipe\discord-ipc-0

**Comment by iCrawl** [comment]
This seems to mainly be an issue with https://github.com/devsnek/discord-rpc

Try running the example in that repo and see if that works, if not do some debugging and open an issue over there.
