### ISSUE TITLE
Breaks after Discord reload

### ISSUE THREAD

**Issue by 1Lighty** [iCrawl/discord-vscode#904]
Version 5.0.0 and over no longer function properly if you reload Discord while it's connected. It says it's connected even if Discord is not running at all which is concerning.

**Steps to reproduce:**
- open Discord and VSCode
- let RPC connect
- CTRL + R in Discord

It used to disconnect when you did that, now it says it's always connected.

Disable, enable, stop, start, reconnect commands do nothing to fix it, only a complete window reload fixes it.

**Comment by iCrawl** [comment]
This should be fixed in 5.2.2
