### ISSUE TITLE
Must have discord open first or else plugin breaks.

### ISSUE THREAD

**Issue by alexacallmebaka** [iCrawl/discord-vscode#905]
Not sure if this behavior is expected, but the extension will only work if I have a Discord window open *before* I open vscode. If I try to open code, then Discord, (or not open Discord at all) the plugin just gets stuck on "Connecting to Discord...". Running Arch Linux with vscode version 1.53.1, Discord Canary (I think), and Plugin version 5.2.2.

**Comment by iCrawl** [comment]
Just use the reconnect command.

**Comment by alexacallmebaka** [comment]
How do I do this? I used to be able to click the plugin in my toolbar but that doesn't do anything. Right-click doesn't do anything either.

**Comment by iCrawl** [comment]
You open the command palette in vscode and look for `Discord: Reconnect`

**Comment by alexacallmebaka** [comment]
Throws the following error: 
![image](https://user-images.githubusercontent.com/50460460/108135042-feeafa00-707c-11eb-860a-872859616ca6.png)
