### ISSUE TITLE
feature request: stop sending events to Discord when window loses focus

### ISSUE THREAD

**Issue by FNCxPro** [iCrawl/discord-vscode#91]
You should be able to check the window focus with an event `vscode.window.onDidChangeWindowState`.

I might take this on and submit a PR but if you get to this first that would be great

**Comment by iCrawl** [comment]
I'd likely avoid this. It just introduces spamming RPC for people who alt-tab a lot.

If you want to keep your editor open 24/7 and not have RPC just deactivate it.

**Comment by FNCxPro** [comment]
I see how that could become an issue very quickly.

Thanks for the insight and the quick response, I'll close because it doesn't seem very smart of a feature to implement :P
