### ISSUE TITLE
Discord shows x hours elapsed straight after starting VSCode

### ISSUE THREAD

**Issue by LitePenguins** [iCrawl/discord-vscode#92]
![image](https://user-images.githubusercontent.com/11067464/45592531-bd971300-b935-11e8-86cd-e1d66dbec645.png)

After launching Visual Studio Code with any file, it shows x hours elapsed even though I just started working on the file. This also happens if I close the current tab and make a new file. The hours seem to change if I restart my PC or relaunch (ex. 08 hours from 06 hours, etc.).

**Comment by FNCxPro** [comment]
I am also experiencing this bug, and another person is. It appears that it only shows that on your end and not anyone elses (this is what it *appears* like)

**Comment by Jayden000** [comment]
I am also experiencing this bug, and as FNC said it looks like it only appears on your end.

**Comment by Hazmi35** [comment]
I am also experiencing this bug, only appears on my end

**Comment by iCrawl** [comment]
Sync your clock, this is not a bug with the extension.

**Comment by Jayden000** [comment]
![image](https://user-images.githubusercontent.com/23621862/45598062-9414d080-b9a3-11e8-805f-5bd91379e731.png)
It says I have been working on it for 20 hours when infact I just opened VS Code. Not sure if it appears as 20 hours on someone elses end

**Comment by iCrawl** [comment]
I can assure you, that's solely on your end because your clock/timezone is out of sync/wrongly configured.

If its not that it's on discord. Anything but the extension because the extension is literally just calling `new Date().getTime()` which is dependent on your system time.

**Comment by Jayden000** [comment]
As you can see by those screenshots it's not my time.

**Comment by FNCxPro** [comment]
See the two screenshots:
* https://cdn.discordapp.com/attachments/397462075141783554/490925450940514304/image0.jpg 
* https://cdn.discordapp.com/attachments/397462075141783554/490925450332471296/image1.jpg

image1.jpg shows me running `ntpdate` to sync to `us.pool.ntp.org`, with a time offset of 0.08 seconds

I installed VSC insiders and Discord Canary just 5 minutes before taking these screenshots

So our clock/timezone is not "out of sync/wrongly configured".

**Comment by iCrawl** [comment]
I also mentioned that this can very well be on discords end, because as you can see the moment you login with another account or someone else is looking at your rich presence the time is correct.

I presented 2 options, not pinpointed it on one.

**Comment by LitePenguins** [comment]
I forgot to mention that I have went into the Windows settings and synced up my clock to the internet time and restarted my computer before checking for the bug again.

**Comment by 0xEAB** [comment]
I don't think this has anything to do with a bad system clock.
If it would, it's still questionable why it started to happen only lately and did occur not before. This does not seem to be a bug introduced by one of the latest Windows updates either because it's happening on Linux, too.

**Comment by iCrawl** [comment]
It only happens if *you* view *your own* presence.

If anyone else views it (even you on the same computer on an alt account), it displays the correct amount.

**Comment by 0xEAB** [comment]
Well, it doesn't seem to occur with my own Rich Presence app...

**Comment by WebFreak001** [comment]
yes the fault lies at the discord library you are using. You are being forced to make the date fit in unix seconds or otherwise the library will complain (`new Date().getTime() / 1000`) while discord expects it to be milliseconds:

https://github.com/iCrawl/discord-vscode/blob/master/src/extension.ts#L265
https://github.com/iCrawl/RPC/blob/master/src/Client.js#L478
https://discordapp.com/developers/docs/topics/gateway#activity-object-activity-timestamps
