### ISSUE TITLE
Update the vscode icon for smallImageKey

### ISSUE THREAD

**Issue by inferno16** [iCrawl/discord-vscode#94]
I really like the extension but there is one thing that is bugging be. It is the old vscode icon used for the smallImageKey (the one with the white background inside the logo). I know I can change the clientID with a custom one and change the icon myself, but that means I'll have to upload every other icon as well and that is not particularly pleasant. Other than that I think it will be a good idea to have the correct icon by default plus you can do that in less than a minute.

P.S. I'm not sure if that applies to the insiders edition as well, but you might want to consider changing it too if that is the case.

**Comment by inferno16** [comment]
I decided to provide you with few images to make your life a little bit easier in case you actually decide that you want to update the icon.

<img width="512" alt="vscode-insiders-uncut" src="https://user-images.githubusercontent.com/2124046/46737984-9964f280-cca5-11e8-9ac9-a2f0a896d96b.png">
<img width="512" alt="vscode-cut" src="https://user-images.githubusercontent.com/2124046/46737985-9964f280-cca5-11e8-9002-635160cf846b.png">
<img width="512" alt="vscode-uncut" src="https://user-images.githubusercontent.com/2124046/46737986-9964f280-cca5-11e8-9ec1-7e173d5927b1.png">
<img width="512" alt="vscode-insiders-cut" src="https://user-images.githubusercontent.com/2124046/46737987-99fd8900-cca5-11e8-91ba-afe166cb8ae3.png">

**Comment by iCrawl** [comment]
I'm not exactly sure what the problem is.
I already use those logos, is it the white inside the logo? 
![image](https://user-images.githubusercontent.com/20760160/46739809-a7187900-cca1-11e8-8c22-f56905f4830a.png)

**Comment by inferno16** [comment]
The ones I uploaded don't have the white background inside the logo as I said in the original post. The white background is really annoying me for some reason. I will understand if you don't want to change them just for that reason.

**Comment by iCrawl** [comment]
No sure, I was just making sure that I was correct in filtering out that information.

I will see how it looks later today, I already went over a lot of small Icon changes but some of them just looked horrible because the icon, as you can see in the screenshot is *really* tiny, and I want to avoid having it be just some wishy-washy thing that you can't make out on the first look.

**Comment by inferno16** [comment]
I made sure to fulfill the Discord's recommendation for a 1024x1024 images, I also used symmetrical resizing in order to fit the images in the canvas and removed the iTXt chunk that photoshop adds to the exported images to reduce the size of the PNGs. I'm pretty sure the icons will render properly, but you might still wanna double check everything if you decide to use my images.

Thanks for the understanding, I'm closing the issue now :)
