### ISSUE TITLE
Disable idling

### ISSUE THREAD

**Issue by orangemn6** [iCrawl/discord-vscode#941]
Hello, I love this extension, but I have one request. Can you please add  an option to disable idling?

**Comment by samwzlim** [comment]
Agreed! One day my friends texted me asking what I was doing on VSCode for 24/7 but it turns out I was just idling on the homescreen, not coding anything. I like to keep vscode open all the time on the homescreen but don't want my discord presence to show that.

**Comment by iCrawl** [comment]
You can disable the idling on an onfocused VSCode now with the new settings key `IdleTimeout`.

Make sure to reload your VSCode every time you change this value.
