### ISSUE TITLE
Linux Discord Connection Not Possible [Fedora 33]

### ISSUE THREAD

**Issue by Max-Rodriguez** [iCrawl/discord-vscode#944]
I recently got my Fedora 33 Workstation setup on a partition on my machine. I synchronized extensions on VScode to have this one enabled on this operating system as well, and it has not been able to connect to my Discord.

It gets stuck at "Connecting to Discord..." as I can see on the bottom bar of the VSCode interface. It seems like it works well on Windows OS but on Linux it is not possible for it to connect to my Discord.

My installation of Discord was installed via the 'snap' package manager on Fedora 33.

**Comment by iCrawl** [comment]
Don't install discord via snap.
