### ISSUE TITLE
Hide bottom bar appearance

### ISSUE THREAD

**Issue by muuvmuuv** [iCrawl/discord-vscode#947]
Please add an option to hide that bottom bar appearance, I am always connected, yes, I don't need any hint for that. If it errors I had got an error anyway.

![Bildschirmfoto 2021-03-12 um 10 15 00](https://user-images.githubusercontent.com/11534760/110918766-ceb11700-831b-11eb-957e-1d71bbad2b44.png)

**Comment by ajs256** [comment]
You can right-click in the status bar to hide it.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/67526318/112909167-bf64f400-90a5-11eb-8c43-eb2ebbd39e6d.png">
