### ISSUE TITLE
Discord Presence no longer displays and cannot reconnect

### ISSUE THREAD

**Issue by jasonZJZhu** [iCrawl/discord-vscode#964]
This extension worked the 1st day I used it but it no longer shows up on Discord. Running the discord.reconnect command results in the following error: 

Command 'Discord Presence: Reconnect Discord Presence to Discord' resulted in an error (Running the contributed command: 'discord.reconnect' failed.)

OS: windows 10 x64
Discord Presence version 5.4
vscode version 1.54.3

**Comment by iCrawl** [comment]
Please read all the other issues on this topics: https://github.com/iCrawl/discord-vscode/issues/85 https://github.com/iCrawl/discord-vscode/issues/943 and many others.
