### ISSUE TITLE
All language names are shown in uppercase

### ISSUE THREAD

**Issue by Follpvosten** [iCrawl/discord-vscode#978]
I noticed this first with "RUST" and thought it was just a common spelling mistake, but apparently all language name are uppercased, which doesn't really make sense to me.
Having looked through the code briefly, I think this could be fixed by either having a map from the language icon name to the appropriate spelling (easy to implement, hard to maintain), or using a casing library and storing the icon names in something like `snake_case`, and then transforming them to `nocase` for loading the file and something like `PascalCase` for the display case (which I think would work for most languages except for maybe Objective-C, and is harder to implement at first, but easier to maintain).

**Comment by Follpvosten** [comment]
Oh well I'm dumb. There's a setting for that.

**Comment by Follpvosten** [comment]
Note that I still think the default should be title case (or PascalCase, really), but that's a different issue.

**Comment by M00TSDNS** [comment]
IMHO the default should be lowercase in the form "Language ID: lang" - this is the most canonical rendering

**Comment by zm-cttae** [comment]
There is a way to compute the actual language alias AKA human-displayed or UI name of language..  
I'll open a PR as soon as possible.
