### ISSUE TITLE
Feature request: Automatic disconnect after X mins/hrs idle

### ISSUE THREAD

**Issue by alystair** [iCrawl/discord-vscode#993]
There are many times I leave VSC open in the background and it simply clocks up unrealistic hours. It'd be great if the extension automatically disconnected after a configurable period of time and then reconnects when focus/activity returns :)

**Comment by iCrawl** [comment]
This is already possible.

**Comment by alystair** [comment]
This is not the same as what I'm asking for @iCrawl - at the moment it switches to an 'idle' mode, while still connected and taking over any potential activity from other sources (such as Spotify, games etc). I want it to fully 'disconnect' from Discord until I return.

**Comment by iCrawl** [comment]
> Time (in seconds) to clear the presence when idling. 0 (the default) means no clearing

This looks exactly like what you want. As long as the window is unfocused, it will clear it after the seconds specified, regaining focus will make it appear again.

**Comment by alystair** [comment]
![image](https://user-images.githubusercontent.com/159109/114434252-cc4b1280-9b90-11eb-8cd7-4e8894b77234.png)
It should be showing Spotify then, not VSC which happens to have been open in the background for quite a bit of time.

**Comment by iCrawl** [comment]
Did you set a proper time in the settings and unfocus your VSCode window?

**Comment by alystair** [comment]
I set it to 60 seconds to test, then restarted VSC.

Before timeout:
![image](https://user-images.githubusercontent.com/159109/114435084-c43fa280-9b91-11eb-8151-51f1f5ee48a5.png)

After timeout:
![image](https://user-images.githubusercontent.com/159109/114435320-079a1100-9b92-11eb-92b3-896dd691b460.png)

Does not disappear from 'playing a game' state.

**Comment by iCrawl** [comment]
That seems to be because you added VSCode in your Discord as a game. This is completely out of my control; you need to remove this.

There is no reason to even add VSCode as a game in Discord, the rich presence will work either way.

**Comment by alystair** [comment]
AHA! I was totally unaware, it was there prior to adding your VSC extension as I wanted 'presence' awareness - I've removed it from my game list and it now works appropriately.

If you wish, I can contribute a FAQ QA for your readme to help others in my position?
